<?php

if(!($this->personIdentity('Person') instanceof \Register\Entity\Person)){
    header('Location: /auth');
    die;
}

$person = $this->getEm()->getRepository('Register\Entity\Person')->find($this->personIdentity('Person')->getId());

echo $this->doctype(); ?>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->basePath(); ?>" />
    <?php
    $title = $this->getConfiguration('Logo');
    echo $this->headTitle($this->translate($title))
        ->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/icons/favicon.ico'
    ));

    $logo = $this->getConfiguration('LOGO');
    $logoAbreviado = $this->getConfiguration('LOGOMINI');
    ?>
    <link href="<?=$this->basePath('/assets/css/jquery-ui.css');?>" rel="stylesheet" />
    <link href="<?=$this->basePath('/assets/css/bootstrap.min.css');?>" rel="stylesheet" />
    <link href="<?=$this->basePath('/assets/css/animate.min.css');?>" rel="stylesheet"/>
    <link href="<?=$this->basePath('/assets/css/light-bootstrap-dashboard.css?v=1.4.0');?>" rel="stylesheet"/>
    <link href="<?=$this->basePath('/assets/css/demo.css" rel="stylesheet');?>" />
    <link href="<?=$this->basePath('/assets/css/pe-icon-7-stroke.css');?>" rel="stylesheet" />
    <link href="<?=$this->basePath('/css/admin/style.css');?>" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

    <script src="<?=$this->basePath('/assets/js/jquery-1.9.1.js');?>" type="text/javascript"></script>
    <script src="<?=$this->basePath('/assets/js/jquery-ui.js');?>" type="text/javascript"></script>
    <script src="<?=$this->basePath('/assets/js/bootstrap.min.js');?>" type="text/javascript"></script>
    <script src="<?=$this->basePath('/assets/js/chartist.min.js');?>"></script>
    <script src="<?=$this->basePath('/assets/js/bootstrap-notify.js');?>"></script>
    <script src="<?=$this->basePath('/assets/js/light-bootstrap-dashboard.js?v=1.4.0');?>"></script>
    <script src="<?=$this->basePath('/assets/js/demo.js');?>"></script>
    <script src="<?=$this->basePath('/js/admin/geral.js')?>"></script>
    <script src="<?=$this->basePath('/js/admin/bootbox.js')?>"></script>
    <script src="<?=$this->basePath('/js/admin/jquery.maskedinput.js')?>"></script>

    <?php

    if($person instanceof \Register\Entity\Person){
        if(!$person->hasThisRole('administrador') && !$person->hasThisRole('empresa')){
            $_SESSION['empresa'] = $person->getCompany()->getId();
        }else if($person->hasThisRole('empresa')){
            $_SESSION['empresa'] = $person->getId();
        }else{
            unset($_SESSION['empresa']);
        }
    }

    ?>
</head>
<body>
    <div class="wrapper">
        <div class="sidebar" data-color="purple" data-image="<?=$this->basePath('/assets/img/sidebar-5.jpg');?>">
            <div class="sidebar-wrapper">
                <div class="logo">
                    <a href="<?=$this->url('admin');?>" class="simple-text">
                        <?=$logo?>
                    </a>
                </div>
                <ul class="nav ">

                    <li class="active">
                        <a href="<?=$this->url('admin');?>">
                            <i class="pe-7s-graph"></i>
                            <p>Dashboard</p>
                        </a>
                    </li>
                    <li id="menu_<?=$a?>" class="nav-item dropdown">
                        <a style="cursor: pointer;" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="pe-7s-box2"></i>
                            <p>Logística</p>
                        </a>
                        <div class="main dropdown-menu">
                            <a class="dropdown-item " href="/admin/data-frete/panel">
                                <i  class="pe-7s-box2"></i> Data Frete
                            </a>
                        </div>
                    </li>

                <?php

                if(!empty($this->getMenu()))
                {
                    foreach($this->getMenu() as $a => $menu)
                    {
                        if(empty($menu['itens']))
                        {
                            ?>
                            <li <?=($_SERVER['REDIRECT_URL'] == $menu['rota'])?'class="active"':''?> >
                                <a href="<?=$menu['rota']?>">
                                    <i class="<?=$menu['icon']?>"></i>
                                    <p><?=$menu['titulo']?></p>
                                </a>
                            </li>
                            <?
                        }else{
                            $somenu = true;

                            ?>
                            <li id="menu_<?=$a?>" class="nav-item dropdown">
                                <a style="cursor: pointer;" class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="<?=$menu['icon']?>"></i>
                                    <p><?=$menu['titulo']?></p>
                                </a>
                                <div class="main dropdown-menu">
                                    <?php
                                    foreach($menu['itens'] as $k => $item)
                                    {
                                        if($item['authorize'] === false){
                                            $authorized = false;
                                            try {
                                                if ($this->authorized($item['titulo'], 'Visualizar') || $this->authorize($item['titulo'], 'Listar')) {
                                                    $authorized = true;
                                                } else {
                                                    continue;
                                                }
                                            }catch(Exception $e){
                                                continue;
                                            }
                                        }
                                        ?>
                                        <a class="dropdown-item " href="<?=$item['rota']?>">
                                            <i  class="<?=$item['icon']?>"></i>  <?=$item['titulo']?>
                                        </a>

                                        <?php
                                        $somenu = false;
                                    }
                                    ?>
                                </div>
                            </li>
                            <?php

                            if($somenu) {
                                ?>
                                <style>
                                    #menu_<?=$a?> {
                                        display: none;
                                    }
                                </style>
                                <?php
                            }
                        }

                    }
                }
                ?>
                </ul>
            </div>
        </div>

        <div class="main-panel">
            <nav class="navbar navbar-default navbar-fixed">
                <div class="container-fluid">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navigation-example-2">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="collapse navbar-collapse">
                        <ul class="nav navbar-nav navbar-right">
                            <li>
                                <a href="/admin/person/edit/<?=$person->getId()?>">
                                    <p><i class="pe-7s-monitor"></i>&nbsp;Site</p>
                                </a>
                            </li>
                            <li>
                                <a href="/admin/person/edit/<?=$person->getId()?>">
                                    <p><i class="pe-7s-user"></i>&nbsp;Meu Cadastro</p>
                                </a>
                            </li>
                            <li>
                                <a href="/auth/logout">
                                    <p><i class="pe-7s-next-2"></i>&nbsp;Deslogar</p>
                                </a>
                            </li>
                            <li class="separator hidden-lg"></li>
                        </ul>
                    </div>
                </div>
            </nav>


            <div class="content">
                <?php
                echo $this->content;
                ?>
            </div>


            <footer class="footer">
                <div class="container-fluid">
                    <p class="copyright pull-right">
                        &copy; <script>document.write(new Date().getFullYear())</script>
                    </p>
                </div>
            </footer>
        </div>
    </div>
</body>
<script type="text/javascript">
    $(document).ready(function(){

        //demo.initChartist();

        // $.notify({
        //     icon: 'pe-7s-gift',
        //     message: "Welcome to <b>Light Bootstrap Dashboard</b> - a beautiful freebie for every web developer."
        //
        // },{
        //     type: 'info',
        //     timer: 4000
        // });

    });

    function alert(msg){
        bootbox.alert(msg);
    }
</script>
</html>