<?php
/**
 *  @var \Admin\Entity\LayoutOption[] $db_layout_options
 *  @var \Admin\Entity\Layout[] $db_layouts
 */
$db_layout_options = $this->getEm()->getRepository('Admin\Entity\LayoutOption')->findAll();
$db_layouts = $this->getEm()->getRepository('Admin\Entity\Layout')->findAll();

$layout_class = '';
if(!empty($db_layouts))
{
    foreach($db_layouts as $db_layout){
        if($db_layout->getActive()){
            $layout_class = $db_layout->getClass();
        }
    }
}

echo $this->doctype(); ?>
<html lang="pt-BR" class="<?=$layout_class?>">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->basePath(); ?>" />
    <?php
    echo $this->headTitle($this->translate($this->getConfiguration('NOMEEMPRESA')))
        ->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/icons/favicon.ico'
    ));

    $person = $this->personIdentity('Person');

    if(!($person instanceof \Register\Entity\Person)){
        header('Location: /auth');
        die;
    }

    if ($person instanceof \Register\Entity\Person) {
        $foto = ($person->getImage() != '' && file_exists('public/img/person/' . $person->getImage())) ? '/img/person/' . $person->getImage() : '/img/person/sem_imagem.jpg';
    }

    if ($this->getConfiguration('LOGO_VERDE')) {
        $logo = ($this->getConfiguration('LOGO_VERDE') != '' && file_exists('public'.$this->getConfiguration('LOGO_VERDE'))) ? $this->getConfiguration('LOGO_VERDE') : '/img/admin/logo.png';
    }

    ?>

    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/font-awesome.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/smartadmin-production-plugins.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/smartadmin-production.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/smartadmin-skins.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/smartadmin-rtl.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/demo.min.css">
    <link rel="shortcut icon" href="/img/admin/favicon/favicon.ico" type="image/x-icon">
    <link rel="icon" href="/img/admin/favicon/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" href="/css/admin/fonts.css?family=Open+Sans:400italic,700italic,300,400,700">
    <link rel="apple-touch-icon" href="/img/admin/splash/sptouch-icon-iphone.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/img/admin/splash/touch-icon-ipad.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/img/admin/splash/touch-icon-iphone-retina.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/img/admin/splash/touch-icon-ipad-retina.png">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/ionicons.min.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/summernote.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/cropper/cropper.css">
    <link rel="stylesheet" type="text/css" media="screen" href="/css/admin/styles.css">

    <script src="/js/admin/jquery.min.js"></script>
    <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body class="desktop-detected pace-done animated fadeIn <?=$layout_class?>">
<header id="header">
    <div id="logo-group">
        <span align="center" id="logo">
            <img  src="<?=$logo?>" alt="SmartAdmin">
        </span>
    </div>
    <div class="pull-right">
        <div id="hide-menu" class="btn-header pull-right">
            <span> <a href="javascript:void(0);" data-action="toggleMenu" title="Collapse Menu"><i class="fa fa-reorder"></i></a> </span>
        </div>
        <ul id="mobile-profile-img" class="header-dropdown-list hidden-xs padding-5">
            <li class="">
                <a href="#" class="dropdown-toggle no-margin userdropdown" data-toggle="dropdown">
                    <img src="/img/admin/avatars/sunny.png" alt="John Doe" class="online" />
                </a>
                <ul class="dropdown-menu pull-right">
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0"><i class="fa fa-cog"></i> Setting</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="profile.html" class="padding-10 padding-top-0 padding-bottom-0"> <i class="fa fa-user"></i> <u>P</u>rofile</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="toggleShortcut"><i class="fa fa-arrow-down"></i> <u>S</u>hortcut</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="javascript:void(0);" class="padding-10 padding-top-0 padding-bottom-0" data-action="launchFullscreen"><i class="fa fa-arrows-alt"></i> Full <u>S</u>creen</a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="login.html" class="padding-10 padding-top-5 padding-bottom-5" data-action="userLogout"><i class="fa fa-sign-out fa-lg"></i> <strong><u>L</u>ogout</strong></a>
                    </li>
                </ul>
            </li>
        </ul>
        <div id="logout" class="btn-header transparent pull-right">
            <span> <a href="/auth/logout" title="Sign Out" data-action="userLogout" data-logout-msg="Para a sua segurança depois de deslogar feche o navegador e abra novamente."><i class="fa fa-sign-out"></i></a> </span>
        </div>
        <div id="search-mobile" class="btn-header transparent pull-right">
            <span> <a href="javascript:void(0)" title="Search"><i class="fa fa-search"></i></a> </span>
        </div>
        <div id="fullscreen" class="btn-header transparent pull-right">
            <span> <a href="javascript:void(0);" data-action="launchFullscreen" title="Full Screen"><i class="fa fa-arrows-alt"></i></a> </span>
        </div>
    </div>
</header>
<aside id="left-panel">
    <div class="login-info">
        <span>
            <a href="javascript:void(0);" id="show-shortcut" data-action="toggleShortcut">
                <img src="<?=$foto?>" alt="me" class="online" />
                <span>
                    <?=$person->getName();?>
                </span>
                <i class="fa fa-angle-down"></i>
            </a>
        </span>
    </div>
    <nav>
        <ul>
            <li class="active open">
                <a href="/admin" title="Dashboard">
                    <i class="fa fa-lg fa-fw fa-home text-info"></i>
                    <span class="menu-item-parent">Dashboard</span>
                </a>
            </li>
            <?php

            if(!empty($this->getMenu()))
            {
                foreach($this->getMenu() as $a => $menu)
                {
                    if(empty($menu['itens']))
                    {
                        ?>
                        <li <?=($_SERVER['REDIRECT_URL'] == $menu['rota'])?'class="active"':''?> >
                            <a href="<?=$menu['rota']?>" title="Dashboard">
                                <i class="<?=$menu['icon']?>"></i>
                                <span class="menu-item-parent"><?=$menu['titulo']?></span>
                            </a>
                        </li>
                        <?
                    }else{
                        $somenu = true;
                        ?>
                        <li id="menu_<?=$a?>" >
                            <a style="cursor: pointer;" >
                                <i class="<?=$menu['icon']?>"></i>
                                <span class="menu-item-parent"><?=$menu['titulo']?></span>
                            </a>
                            <ul>
                                <?php
                                foreach($menu['itens'] as $k => $item)
                                {
                                    if($item['authorize'] === false){
                                        $authorized = false;
                                        try {
                                            if ($this->authorized($item['titulo'], 'Visualizar') || $this->authorize($item['titulo'], 'Listar')) {
                                                $authorized = true;
                                            } else {
                                                continue;
                                            }
                                        }catch(Exception $e){
                                            continue;
                                        }
                                    }
                                    ?>
                                    <li>
                                        <a href="<?=$item['rota']?>" title="<?=$item['titulo']?>">
                                            <span class="menu-item-parent"><?=$item['titulo']?></span>
                                        </a>
                                    </li>
                                    <?php
                                    $somenu = false;
                                }
                                ?>
                            </ul>
                        </li>
                        <?php

                        if($somenu) {
                            ?>
                            <style>
                                #menu_<?=$a?> {
                                    display: none;
                                }
                            </style>
                            <?php
                        }
                    }

                }
            }
            ?>
        </ul>
    </nav>
    <span class="minifyme" data-action="minifyMenu">
        <i class="fa fa-arrow-circle-left hit"></i>
    </span>
</aside>
<div id="main" role="main">
    <?=$this->content;?>
</div>
<div class="page-footer">
    <div class="row">
        <div class="col-xs-12 col-sm-6">
            <span class="txt-color-white">Inovens TI. <span class="hidden-xs"> - Fábrica de Software</span> © 2018-<?=date('Y')?></span>
        </div>
    </div>
</div>
<?php
$url_edit = '';
if($person->hasThisRole('administrador')){
    $url_edit = '/admin/administrator/edit/'.$person->getId();
}else  if($person->hasThisRole('empresa')){
    $url_edit = '/admin/company/edit/'.$person->getId();
}else if($person->hasThisRole('funcionario')){
    $url_edit = '/admin/employee/edit/'.$person->getId();
}else if($person->hasThisRole('cliente')){
    $url_edit = '/admin/customer/edit/'.$person->getId();
}else{
    $url_edit = '/admin/customer/edit/'.$person->getId();
}
?>
<div id="shortcut">
    <ul>
        <li>
            <a href="<?=$url_edit?>" class="jarvismetro-tile big-cubes selected bg-color-pinkDark"> <span class="iconbox"> <i class="fa fa-user fa-4x"></i> <span>Meu Cadastro</span> </span> </a>
        </li>
    </ul>
</div>

</body>
<script data-pace-options='{ "restartOnRequestAfter": true }' src="/js/admin/plugin/pace/pace.min.js"></script>
<script>
    if (!window.jQuery) {
        document.write('<script src="/js/admin/libs/jquery-3.2.1.min.js"><\/script>');
    }
</script>
<script src="/js/admin/jquery-ui.min.js"></script>
<script>
    if (!window.jQuery.ui) {
        document.write('<script src="/js/admin/libs/jquery-ui.min.js"><\/script>');
    }
</script>
<script src="/js/admin/app.config.js"></script>
<script src="/js/admin/plugin/jquery-touch/jquery.ui.touch-punch.min.js"></script>
<script src="/js/admin/bootstrap/bootstrap.min.js"></script>
<script src="/js/admin/notification/SmartNotification.min.js"></script>
<script src="/js/admin/smartwidgets/jarvis.widget.min.js"></script>
<script src="/js/admin/plugin/easy-pie-chart/jquery.easy-pie-chart.min.js"></script>
<script src="/js/admin/plugin/sparkline/jquery.sparkline.min.js"></script>
<script src="/js/admin/plugin/jquery-validate/jquery.validate.min.js"></script>
<script src="/js/admin/plugin/masked-input/jquery.maskedinput.min.js"></script>
<script src="/js/admin/plugin/select2/select2.min.js"></script>
<script src="/js/admin/plugin/bootstrap-slider/bootstrap-slider.min.js"></script>
<script src="/js/admin/plugin/msie-fix/jquery.mb.browser.min.js"></script>
<script src="/js/admin/plugin/fastclick/fastclick.min.js"></script>
<!--[if IE 8]>

<h1>Your browser is out of date, please update your browser by going to www.microsoft.com/download</h1>

<![endif]-->
<script src="/js/admin/demo.min.js"></script>
<script src="/js/admin/app.min.js"></script>
<script src="/js/admin/speech/voicecommand.min.js"></script>
<script src="/js/admin/smart-chat-ui/smart.chat.ui.min.js"></script>
<script src="/js/admin/smart-chat-ui/smart.chat.manager.min.js"></script>
<script src="/js/admin/plugin/flot/jquery.flot.cust.min.js"></script>
<script src="/js/admin/plugin/flot/jquery.flot.resize.min.js"></script>
<script src="/js/admin/plugin/flot/jquery.flot.time.min.js"></script>
<script src="/js/admin/plugin/flot/jquery.flot.tooltip.min.js"></script>
<script src="/js/admin/plugin/vectormap/jquery-jvectormap-1.2.2.min.js"></script>
<script src="/js/admin/plugin/vectormap/jquery-jvectormap-world-mill-en.js"></script>
<script src="/js/admin/plugin/moment/moment.min.js"></script>
<script src="/js/admin/plugin/fullcalendar/fullcalendar.min.js"></script>
<script src="/js/admin/bootbox.js"></script>
<script src="/js/admin/summernote.js"></script>
<script src="/js/admin/cropper/cropper.min.js"></script>
<script src="/js/admin/geral.js"></script>
<script src="/js/admin/bootstrap-notify.js"></script>
<script src="/js/admin/JsBarcode.all.min.js"></script>
<script>
    function setCookie(cname, cvalue, exdays) {
        var d = new Date();
        d.setTime(d.getTime() + (exdays * 24 * 60 * 60 * 1000));
        var expires = "expires="+d.toUTCString();
        document.cookie = cname + "=" + cvalue + ";" + expires + ";path=/";
    }

    function getCookie(cname) {
        var name = cname + "=";
        var ca = document.cookie.split(';');
        for(var i = 0; i < ca.length; i++) {
            var c = ca[i];
            while (c.charAt(0) == ' ') {
                c = c.substring(1);
            }
            if (c.indexOf(name) == 0) {
                return c.substring(name.length, c.length);
            }
        }
        return "";
    }

    function checkCookie() {
        var user = getCookie("username");
        if (user != "") {
            alert("Welcome again " + user);
        } else {
            user = prompt("Please enter your name:", "");
            if (user != "" && user != null) {
                setCookie("username", user, 365);
            }
        }
    }

    $( ".demo input[type=checkbox]" ).each(function( index ) {
        if(this.id != 'smart-topmenu') {
            if (getCookie(this.id) == 'true') {
                $(this).trigger('click');
            }
        }
    });

    $( ".demo input[type=checkbox]" ).click(function(){
        if (getCookie(this.id) == 'true') {
            setCookie(this.id, 'false', 365);
        }else{
            setCookie(this.id, 'true', 365)
        }
    });

    function alert(msg){
        bootbox.alert(msg);
    }

    $(document).ready(function() {

        // DO NOT REMOVE : GLOBAL FUNCTIONS!
        pageSetUp();

        /*
         * PAGE RELATED SCRIPTS
         */

        $(".js-status-update a").click(function() {
            var selText = $(this).text();
            var $this = $(this);
            $this.parents('.btn-group').find('.dropdown-toggle').html(selText + ' <span class="caret"></span>');
            $this.parents('.dropdown-menu').find('li').removeClass('active');
            $this.parent().addClass('active');
        });

        // initialize sortable
        $(function() {
            $("#sortable1, #sortable2").sortable({
                handle : '.handle',
                connectWith : ".todo",
                update : countTasks
            }).disableSelection();
        });

        // check and uncheck
        $('.todo .checkbox > input[type="checkbox"]').click(function() {
            var $this = $(this).parent().parent().parent();

            if ($(this).prop('checked')) {
                $this.addClass("complete");

                // remove this if you want to undo a check list once checked
                //$(this).attr("disabled", true);
                $(this).parent().hide();

                // once clicked - add class, copy to memory then remove and add to sortable3
                $this.slideUp(500, function() {
                    $this.clone().prependTo("#sortable3").effect("highlight", {}, 800);
                    $this.remove();
                    countTasks();
                });
            } else {
                // insert undo code here...
            }

        })
        // count tasks
        function countTasks() {

            $('.todo-group-title').each(function() {
                var $this = $(this);
                $this.find(".num-of-tasks").text($this.next().find("li").size());
            });

        }

        /*
        * RUN PAGE GRAPHS
        */

        /* TAB 1: UPDATING CHART */
        // For the demo we use generated data, but normally it would be coming from the server

        var data = [], totalPoints = 200, $UpdatingChartColors = $("#updating-chart").css('color');

        function getRandomData() {
            if (data.length > 0)
                data = data.slice(1);

            // do a random walk
            while (data.length < totalPoints) {
                var prev = data.length > 0 ? data[data.length - 1] : 50;
                var y = prev + Math.random() * 10 - 5;
                if (y < 0)
                    y = 0;
                if (y > 100)
                    y = 100;
                data.push(y);
            }

            // zip the generated y values with the x values
            var res = [];
            for (var i = 0; i < data.length; ++i)
                res.push([i, data[i]])
            return res;
        }

        // setup control widget
        var updateInterval = 1500;
        $("#updating-chart").val(updateInterval).change(function() {

            var v = $(this).val();
            if (v && !isNaN(+v)) {
                updateInterval = +v;
                $(this).val("" + updateInterval);
            }

        });

        // setup plot
        var options = {
            yaxis : {
                min : 0,
                max : 100
            },
            xaxis : {
                min : 0,
                max : 100
            },
            colors : [$UpdatingChartColors],
            series : {
                lines : {
                    lineWidth : 1,
                    fill : true,
                    fillColor : {
                        colors : [{
                            opacity : 0.4
                        }, {
                            opacity : 0
                        }]
                    },
                    steps : false

                }
            }
        };

        var plot = $.plot($("#updating-chart"), [getRandomData()], options);

        /* live switch */
        $('input[type="checkbox"]#start_interval').click(function() {
            if ($(this).prop('checked')) {
                $on = true;
                updateInterval = 1500;
                update();
            } else {
                clearInterval(updateInterval);
                $on = false;
            }
        });

        function update() {
            if ($on == true) {
                plot.setData([getRandomData()]);
                plot.draw();
                setTimeout(update, updateInterval);

            } else {
                clearInterval(updateInterval)
            }

        }

        var $on = false;

        $(function() {
            // jQuery Flot Chart
            var twitter = [[1, 27], [2, 34], [3, 51], [4, 48], [5, 55], [6, 65], [7, 61], [8, 70], [9, 65], [10, 75], [11, 57], [12, 59], [13, 62]], facebook = [[1, 25], [2, 31], [3, 45], [4, 37], [5, 38], [6, 40], [7, 47], [8, 55], [9, 43], [10, 50], [11, 47], [12, 39], [13, 47]], data = [{
                label : "Twitter",
                data : twitter,
                lines : {
                    show : true,
                    lineWidth : 1,
                    fill : true,
                    fillColor : {
                        colors : [{
                            opacity : 0.1
                        }, {
                            opacity : 0.13
                        }]
                    }
                },
                points : {
                    show : true
                }
            }, {
                label : "Facebook",
                data : facebook,
                lines : {
                    show : true,
                    lineWidth : 1,
                    fill : true,
                    fillColor : {
                        colors : [{
                            opacity : 0.1
                        }, {
                            opacity : 0.13
                        }]
                    }
                },
                points : {
                    show : true
                }
            }];

            var options = {
                grid : {
                    hoverable : true
                },
                colors : ["#568A89", "#3276B1"],
                tooltip : true,
                tooltipOpts : {
                    //content : "Value <b>$x</b> Value <span>$y</span>",
                    defaultTheme : false
                },
                xaxis : {
                    ticks : [[1, "JAN"], [2, "FEB"], [3, "MAR"], [4, "APR"], [5, "MAY"], [6, "JUN"], [7, "JUL"], [8, "AUG"], [9, "SEP"], [10, "OCT"], [11, "NOV"], [12, "DEC"], [13, "JAN+1"]]
                },
                yaxes : {

                }
            };

            var plot3 = $.plot($("#statsChart"), data, options);
        });

        $(function() {

            var trgt = [[1354586000000, 153], [1364587000000, 658], [1374588000000, 198], [1384589000000, 663], [1394590000000, 801], [1404591000000, 1080], [1414592000000, 353], [1424593000000, 749], [1434594000000, 523], [1444595000000, 258], [1454596000000, 688], [1464597000000, 364]], prft = [[1354586000000, 53], [1364587000000, 65], [1374588000000, 98], [1384589000000, 83], [1394590000000, 980], [1404591000000, 808], [1414592000000, 720], [1424593000000, 674], [1434594000000, 23], [1444595000000, 79], [1454596000000, 88], [1464597000000, 36]], sgnups = [[1354586000000, 647], [1364587000000, 435], [1374588000000, 784], [1384589000000, 346], [1394590000000, 487], [1404591000000, 463], [1414592000000, 479], [1424593000000, 236], [1434594000000, 843], [1444595000000, 657], [1454596000000, 241], [1464597000000, 341]], toggles = $("#rev-toggles"), target = $("#flotcontainer");

            var data = [{
                label : "Target Profit",
                data : trgt,
                bars : {
                    show : true,
                    align : "center",
                    barWidth : 30 * 30 * 60 * 1000 * 80
                }
            }, {
                label : "Actual Profit",
                data : prft,
                color : '#3276B1',
                lines : {
                    show : true,
                    lineWidth : 3
                },
                points : {
                    show : true
                }
            }, {
                label : "Actual Signups",
                data : sgnups,
                color : '#71843F',
                lines : {
                    show : true,
                    lineWidth : 1
                },
                points : {
                    show : true
                }
            }]

            var options = {
                grid : {
                    hoverable : true
                },
                tooltip : true,
                tooltipOpts : {
                    //content: '%x - %y',
                    //dateFormat: '%b %y',
                    defaultTheme : false
                },
                xaxis : {
                    mode : "time"
                },
                yaxes : {
                    tickFormatter : function(val, axis) {
                        return "$" + val;
                    },
                    max : 1200
                }

            };

            plot2 = null;

            function plotNow() {
                var d = [];
                toggles.find(':checkbox').each(function() {
                    if ($(this).is(':checked')) {
                        d.push(data[$(this).attr("name").substr(4, 1)]);
                    }
                });
                if (d.length > 0) {
                    if (plot2) {
                        plot2.setData(d);
                        plot2.draw();
                    } else {
                        plot2 = $.plot(target, d, options);
                    }
                }

            };

            toggles.find(':checkbox').on('change', function() {
                plotNow();
            });
            plotNow()

        });

        data_array = {
            "US" : 4977,
            "AU" : 4873,
            "IN" : 3671,
            "BR" : 2476,
            "TR" : 1476,
            "CN" : 146,
            "CA" : 134,
            "BD" : 100
        };

        $('#vector-map').vectorMap({
            map : 'world_mill_en',
            backgroundColor : '#fff',
            regionStyle : {
                initial : {
                    fill : '#c4c4c4'
                },
                hover : {
                    "fill-opacity" : 1
                }
            },
            series : {
                regions : [{
                    values : data_array,
                    scale : ['#85a8b6', '#4d7686'],
                    normalizeFunction : 'polynomial'
                }]
            },
            onRegionLabelShow : function(e, el, code) {
                if ( typeof data_array[code] == 'undefined') {
                    e.preventDefault();
                } else {
                    var countrylbl = data_array[code];
                    el.html(el.html() + ': ' + countrylbl + ' visits');
                }
            }
        });

        if ($("#calendar").length) {
            var date = new Date();
            var d = date.getDate();
            var m = date.getMonth();
            var y = date.getFullYear();

            var calendar = $('#calendar').fullCalendar({

                editable : true,
                draggable : true,
                selectable : false,
                selectHelper : true,
                unselectAuto : false,
                disableResizing : false,
                height: "auto",

                header : {
                    left : 'title', //,today
                    center : 'prev, next, today',
                    right : 'month, agendaWeek, agenDay' //month, agendaDay,
                },

                select : function(start, end, allDay) {
                    var title = prompt('Event Title:');
                    if (title) {
                        calendar.fullCalendar('renderEvent', {
                                title : title,
                                start : start,
                                end : end,
                                allDay : allDay
                            }, true // make the event "stick"
                        );
                    }
                    calendar.fullCalendar('unselect');
                },

                events : [{
                    title : 'All Day Event',
                    start : new Date(y, m, 1),
                    description : 'long description',
                    className : ["event", "bg-color-greenLight"],
                    icon : 'fa-check'
                }, {
                    title : 'Long Event',
                    start : new Date(y, m, d - 5),
                    end : new Date(y, m, d - 2),
                    className : ["event", "bg-color-red"],
                    icon : 'fa-lock'
                }, {
                    id : 999,
                    title : 'Repeating Event',
                    start : new Date(y, m, d - 3, 16, 0),
                    allDay : false,
                    className : ["event", "bg-color-blue"],
                    icon : 'fa-clock-o'
                }, {
                    id : 999,
                    title : 'Repeating Event',
                    start : new Date(y, m, d + 4, 16, 0),
                    allDay : false,
                    className : ["event", "bg-color-blue"],
                    icon : 'fa-clock-o'
                }, {
                    title : 'Meeting',
                    start : new Date(y, m, d, 10, 30),
                    allDay : false,
                    className : ["event", "bg-color-darken"]
                }, {
                    title : 'Lunch',
                    start : new Date(y, m, d, 12, 0),
                    end : new Date(y, m, d, 14, 0),
                    allDay : false,
                    className : ["event", "bg-color-darken"]
                }, {
                    title : 'Birthday Party',
                    start : new Date(y, m, d + 1, 19, 0),
                    end : new Date(y, m, d + 1, 22, 30),
                    allDay : false,
                    className : ["event", "bg-color-darken"]
                }, {
                    title : 'Smartadmin Open Day',
                    start : new Date(y, m, 28),
                    end : new Date(y, m, 29),
                    className : ["event", "bg-color-darken"]
                }],


                eventRender : function(event, element, icon) {
                    if (!event.description == "") {
                        element.find('.fc-title').append("<br/><span class='ultra-light'>" + event.description + "</span>");
                    }
                    if (!event.icon == "") {
                        element.find('.fc-title').append("<i class='air air-top-right fa " + event.icon + " '></i>");
                    }
                }
            });

        };

        /* hide default buttons */
        $('.fc-toolbar .fc-right, .fc-toolbar .fc-center').hide();

        // calendar prev
        $('#calendar-buttons #btn-prev').click(function() {
            $('.fc-prev-button').click();
            return false;
        });

        // calendar next
        $('#calendar-buttons #btn-next').click(function() {
            $('.fc-next-button').click();
            return false;
        });

        // calendar today
        $('#calendar-buttons #btn-today').click(function() {
            $('.fc-button-today').click();
            return false;
        });

        // calendar month
        $('#mt').click(function() {
            $('#calendar').fullCalendar('changeView', 'month');
        });

        // calendar agenda week
        $('#ag').click(function() {
            $('#calendar').fullCalendar('changeView', 'agendaWeek');
        });

        // calendar agenda day
        $('#td').click(function() {
            $('#calendar').fullCalendar('changeView', 'agendaDay');
        });

        $.filter_input = $('#filter-chat-list');
        $.chat_users_container = $('#chat-container > .chat-list-body')
        $.chat_users = $('#chat-users')
        $.chat_list_btn = $('#chat-container > .chat-list-open-close');
        $.chat_body = $('#chat-body');

        // custom css expression for a case-insensitive contains()
        jQuery.expr[':'].Contains = function(a, i, m) {
            return (a.textContent || a.innerText || "").toUpperCase().indexOf(m[3].toUpperCase()) >= 0;
        };

        function listFilter(list) {// header is any element, list is an unordered list
            // create and add the filter form to the header

            $.filter_input.change(function() {
                var filter = $(this).val();
                if (filter) {
                    // this finds all links in a list that contain the input,
                    // and hide the ones not containing the input while showing the ones that do
                    $.chat_users.find("a:not(:Contains(" + filter + "))").parent().slideUp();
                    $.chat_users.find("a:Contains(" + filter + ")").parent().slideDown();
                } else {
                    $.chat_users.find("li").slideDown();
                }
                return false;
            }).keyup(function() {
                $(this).change();
            });
        }

        // on dom ready
        listFilter($.chat_users);

        // open chat list
        $.chat_list_btn.click(function() {
            $(this).parent('#chat-container').toggleClass('open');
        })

        $.chat_body.animate({
            scrollTop : $.chat_body[0].scrollHeight
        }, 500);

    });



    </script>
</html>