<?php
echo $this->doctype(); ?>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->basePath(); ?>" />
    <?php
    $title = $this->getConfiguration('Logo');
    echo $this->headTitle($this->translate($title))
        ->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink(array(
        'rel' => 'shortcut icon',
        'type' => 'image/vnd.microsoft.icon',
        'href' => $this->basePath() . '/img/icons/favicon.ico'
    ));


    $person = $this->personIdentity('Person');

    if(!($person instanceof \Register\Entity\Person)){
        header('Location: /auth');
        die;
    }

    $logo = $this->getConfiguration('LOGO');
    $logoAbreviado = $this->getConfiguration('LOGOMINI');
    ?>
    <link href="<?=$this->basePath('/assets/css/bootstrap.min.css');?>" rel="stylesheet" />
    <link href="<?=$this->basePath('/assets/css/animate.min.css');?>" rel="stylesheet"/>
    <link href="<?=$this->basePath('/assets/css/light-bootstrap-dashboard.css?v=1.4.0');?>" rel="stylesheet"/>
    <link href="<?=$this->basePath('/assets/css/demo.css" rel="stylesheet');?>" />
    <link href="<?=$this->basePath('/assets/css/pe-icon-7-stroke.css');?>" rel="stylesheet" />
    <link href="<?=$this->basePath('/css/admin/style.css');?>" rel="stylesheet" />
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,700,300' rel='stylesheet' type='text/css'>

    <script src="<?=$this->basePath('/assets/js/jquery.3.2.1.min.js');?>" type="text/javascript"></script>
    <script src="<?=$this->basePath('/assets/js/bootstrap.min.js');?>" type="text/javascript"></script>
    <script src="<?=$this->basePath('/assets/js/chartist.min.js');?>"></script>
    <script src="<?=$this->basePath('/assets/js/bootstrap-notify.js');?>"></script>
    <script src="<?=$this->basePath('/assets/js/light-bootstrap-dashboard.js?v=1.4.0');?>"></script>
    <script src="<?=$this->basePath('/assets/js/demo.js');?>"></script>
    <script src="<?=$this->basePath('/js/admin/geral.js')?>"></script>
    <script src="<?=$this->basePath('/js/admin/bootbox.js')?>"></script>
</head>
<body>
<div class="content">
    <?php
    echo $this->content;
    ?>
</div>
</body>
<script type="text/javascript">
    function alert(msg){
        bootbox.alert(msg);
    }
</script>
</html>