<?php
echo $this->doctype(); ?>
<html lang="pt-BR">
<head>
    <meta charset="utf-8">
    <base href="<?php echo $this->basePath(); ?>" />
    <?php
    $title = $this->getConfiguration('Logo');
    echo $this->headTitle($this->translate($title))
        ->setSeparator(' - ')->setAutoEscape(false);

    echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

    echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/icons/favicon.ico'))
        ->prependStylesheet($this->basePath('css/admin/cropper/cropper.css'))
        ->prependStylesheet($this->basePath('css/admin/summernote.css'))
        ->prependStylesheet($this->basePath('css/admin/dataTables.bootstrap.css'))
        ->prependStylesheet($this->basePath('css/admin/style.css'))
        ->prependStylesheet($this->basePath('css/admin/styles-front.css'))
        ->prependStylesheet($this->basePath('css/admin/jquery-ui.css'))
        ->prependStylesheet($this->basePath('css/admin/bootstrap3-wysihtml5.min.css'))
        ->prependStylesheet($this->basePath('css/admin/daterangepicker-bs3.css'))
        ->prependStylesheet($this->basePath('css/admin/datepicker3.css'))
        ->prependStylesheet($this->basePath('css/admin/jquery-jvectormap-1.2.2.css'))
        ->prependStylesheet($this->basePath('css/admin/morris.css'))
        ->prependStylesheet($this->basePath('css/admin/blue.css'))
        ->prependStylesheet($this->basePath('css/admin/all.css'))
        ->prependStylesheet($this->basePath('css/admin/_all.css'))
        ->prependStylesheet($this->basePath('css/admin/_all-skins.min.css'))
        ->prependStylesheet($this->basePath('css/admin/AdminLTE.min.css'))
        ->prependStylesheet($this->basePath('css/admin/ionicons.min.css'))
        ->prependStylesheet($this->basePath('css/admin/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/admin/bootstrap.min.css'));

    echo $this->headScript()
        ->prependFile($this->basePath('js/admin/cropper/cropper.min.js'))
        ->prependFile($this->basePath('js/admin/summernote.js'))
        ->prependFile($this->basePath('js/admin/bootbox.js'))
        ->prependFile($this->basePath('js/admin/demo.js'))
        ->prependFile($this->basePath('js/admin/dashboard.js'))
        ->prependFile($this->basePath('js/admin/Chart.min.js'))
        ->prependFile($this->basePath('js/admin/app.min.js'))
        ->prependFile($this->basePath('js/admin/fastclick.min.js'))
        ->prependFile($this->basePath('js/admin/daterangepicker.js'))
        ->prependFile($this->basePath('js/admin/moment.js'))
        ->prependFile($this->basePath('js/admin/raphael-min.js'))
        ->prependFile($this->basePath('js/admin/bootstrap3-wysihtml5.all.min.js'))
        ->prependFile($this->basePath('js/admin/bootstrap-datepicker.js'))
        ->prependFile($this->basePath('js/admin/bootstrap.js'))
        ->prependFile($this->basePath('js/admin/icheck.js'))
        ->prependFile($this->basePath('js/admin/jquery.slimscroll.min.js'))
        ->prependFile($this->basePath('js/admin/jquery.dataTables.min.js'))
        ->prependFile($this->basePath('js/admin/jquery.knob.js'))
        ->prependFile($this->basePath('js/admin/jquery.maskedinput.js'))
        ->prependFile($this->basePath('/js/admin/jquery-jvectormap-world-mill-en.js'))
        ->prependFile($this->basePath('js/admin/jquery-jvectormap-1.2.2.min.js'))
        ->prependFile($this->basePath('js/admin/jquery.sparkline.min.js'))
        ->prependFile($this->basePath('js/admin/jquery.inputmask.date.extensions.js'))
        ->prependFile($this->basePath('js/admin/jquery.inputmask.js'))
        ->prependFile($this->basePath('js/admin/jquery.maskMoney.js'))
        ->prependFile($this->basePath('js/admin/jquery-ui.min.js'))
        ->prependFile($this->basePath('js/admin/jquery.js'));

    $person = $this->personIdentity('Person');

    if(!($person instanceof \Register\Entity\Person)){
        header('Location: /auth');
        die;
    }

    $logo = $this->getConfiguration('LOGO');
    $logoAbreviado = $this->getConfiguration('LOGOMINI');
    $personPicture = $this->personPicture($person);

    ?>
    <script>
        $.widget.bridge('uibutton', $.ui.button);
        function alert(msg){
            bootbox.alert(msg);
        }
    </script>

</head>
<body class="hold-transition skin-blue sidebar-mini">
    <div class="wrapper">
        <header class="main-header">
            <a href="/admin" class="logo center">
                <span class="logo-mini">
                    <?=($logoAbreviado!=false)?$logoAbreviado:'<i class="fa fa-dashboard"></i>'?>
                </span>
                <span class="logo-lg">
                    <?=$logo?>
                </span>
            </a>
            <nav class="navbar navbar-static-top" role="navigation">
                <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu ">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                <img src="<?=$personPicture?>" class="user-image" alt="User Image">
                                <span class="hidden-xs"><?=$person->getName()?></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- User image -->
                                <li class="user-header">
                                    <img src="<?=$personPicture?>" class="img-circle" alt="User Image">
                                    <p>
                                        <small>Membro desde <?=$person->getCreatedAt()->format('d/m/Y')?></small>
                                    </p>
                                </li>
                                <!-- Menu Body -->
                                <li style="display:none" class="user-body">
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Followers</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Sales</a>
                                    </div>
                                    <div class="col-xs-4 text-center">
                                        <a href="#">Friends</a>
                                    </div>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="/admin/person/edit/<?=$person->getId()?>" class="btn btn-default btn-flat">Informações</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="/auth/logout" class="btn btn-default btn-flat">Deslogar</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <div class="user-panel">
                    <div style="position: relative" class="pull-left image">
                        <a class="edit-photo"
                           href="<?= $this->url('person/default', array('controller' => 'person', 'action' => 'edit', 'id' => $person->getId())) ?>#Inputimage">
                            <i class="fa fa-edit"></i>
                        </a>
                        <div style="background-image: url('<?=$personPicture?>'); width: 45px; height: 45px;background-position: center;background-size: cover"  class="img-circle foto-cliente" ></div>
                    </div>
                    <div class="pull-left info">
                        <p><?=$person->getName()?></p>
                        <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
                    </div>
                </div>
    
                <form style="display:none" action="#" method="get" class="sidebar-form">
                    <div class="input-group">
                        <input type="text" name="q" class="form-control" placeholder="Pesquisar...">
                          <span class="input-group-btn">
                            <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i></button>
                          </span>
                    </div>
                </form>
    
                <ul class="sidebar-menu">
                    <li class="header">MENU PRINCIPAL</li>
                    <?
                    $menu = $this->getMenu();
                    if(!empty($menu)){
                        foreach($menu as $id => $categorias){
                            ?>
                            <li id="<?=$id?>"  class="<?=($categorias['active'])?'active':'';?> treeview">
                                <a href="<?=(isset($categorias['rota']))?$categorias['rota']:'#'?>">
                                    <i class="<?=$categorias['icon']?>"></i> <span><?=$categorias['titulo']?></span> <?=(!isset($categorias['rota']) && !empty($categorias['itens']))?'<i class="fa fa-angle-left pull-right"></i>':''?>
                                </a>
                                <?
                                $contador = 0;
                                if(!empty($categorias['itens'])){
                                    ?>
                                    <ul class="treeview-menu">
                                        <?
    
                                        foreach($categorias['itens'] as $chave => $item){
                                            if(!$item['authorize']){
                                                if($this->personPermission('modulos',$chave,'listAll')) {
                                                    ?>
                                                    <li>
                                                        <a href="<?=$item['rota']?>">
                                                            <i class="<?=$item['icon']?>"></i> <?=$item['titulo']?>
                                                        </a>
                                                    </li>
                                                    <?
                                                    $contador++;
                                                }
                                            }else{
                                                ?>
                                                <li>
                                                    <a href="<?=$item['rota']?>">
                                                        <i class="<?=$item['icon']?>"></i> <?=$item['titulo']?>
                                                    </a>
                                                </li>
                                                <?
                                                $contador++;
                                            }
                                        }
                                        ?>
                                    </ul>
                                    <?
                                }
    
                                if($contador < 1 && !isset($categorias['rota'])){
                                    ?>
                                    <style>
                                        #<?=$id?>{
                                            display: none;
                                        }
                                    </style>
                                    <?
                                }
    
                                ?>
                            </li>
                            <?
                        }
                    }
                    ?>
                </ul>
            </section>
        </aside>
        <div class="content-wrapper">
            <?php
            echo $this->content;
            ?>
        </div>
        <footer class="main-footer">
            <div class="pull-right hidden-xs">
                <b>Todos os Direitos Reservados. CNPJ: 00.000.000/0000-00</b>
            </div>
            <strong><a href="http://www.google.com/">© Nome da Empresa 2015 - 2016.</a></strong>
        </footer>
    </div>
</body>
<script src="<?=$this->basePath("/js/admin/geral.js")?>"></script>
</html>