<section class="content-header">
    <h1>
        <?=$this->data_page['title']?> - <small>Cadastre, atulize, recorte imagens</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('admin');?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li><a href="<?=$this->url($this->controller.'/default',array('controller' => $this->controller,'action' => 'index'));?>">Clientes</a></li>
        <li class="active">Imagens</li>
    </ol>
</section>
<br /><br />
<?php
//Definido em Register/config/module.config.php
//template_map => 'image-interface' => __DIR__ . '/../view/partials/image-interface.phtml'
echo $this->partial('image-interface',array(
    'data_page' => $this->data_page,
    'entity' => $this->entity,
    'db_person' => $this->db_person,
    'controller' => $this->controller,
    'em' => $em,
    'id' => $this->id,
    'aspectRatio' => '9 / 16'
));
?>
