<!-- Content Header (Page header) -->
<!-- Content Header (Page header) -->

<section class="content-header">
	<h1>
		<?=$this->translate("Usuários");?>
		<small><?=$this->translate("Listagem de usuários cadastrados");?></small>
	</h1>
	<ol class="breadcrumb">
		<li>
			<a href="/admin"><i class="fa fa-dashboard"></i> Home</a>
		</li>
		<li class="active">
			<?=$this->translate("Usuários");?>
		</li>
	</ol>
</section>
<?php

$links['new'] = $this->url('person/default',array('controller'=>'person','action'=>'new'));
?>
<br />
<div class="row">
    <div class="col-md-12">
        <div class="col-md-6 pull-right">
            <div class="box box-primary">
                <div class="box-header with-border">
                	<h3 class="box-title"><i class="fa fa-filter"></i> <?=$this->translate("Filtro");?></h3>
                </div>
                <form id="filter_form" method="POST" action="" role="form">
                    <div class="box-body">
                        <div class="form-group">
                            <label for="filterName"><?=$this->translate("Nome");?></label>
                            <input type="text" name="name" id="filterName" class="form-control" value="<?=(isset($_POST['name']))?$_POST['name']:'';?>">
                        </div>    
                    </div><!-- /.box-body -->
                    <div class="box-footer">
                    	<button name="filter" type="submit" class="btn btn-primary"><?=$this->translate("Filtrar");?></button>
                    </div>
                </form>
            </div><!-- /.box -->
        </div>
    </div>
</div>
<div class="row">
    <div  class="col-md-12">   
		<div class="col-md-12">
			<br />
			<div class="box">
                <div class="box-header">
                    <h3 class="box-title">
                    	<i class="fa fa-users"></i> <?=$this->translate("Usuários");?>
                    </h3>                    
                    <div class="box-tools">
                        <div style="float: left;margin-right: 10px;" class="btn-group">                  		
                        	<a href="<?=$links['new']?>">
                        		<button type="button" class="btn btn-success"><i class="fa fa-plus"></i> <?=$this->translate("Novo");?></button>
                        	</a>                    	
                        </div>                                       
                    </div>
                </div>
                <br />
                <div class="container">
                	<div class="row">
                        <div class="col-md-12 flashMessages">
                            <?php
                             $flash  =  $this->flashMessenger (); 
                             echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' )); 
                             echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' )); 
                             echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' )); 
                             echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));
                             ?>
                        </div>
                	</div>
                </div>
                <br />
                <div class="box-body table-responsive no-padding">
					<table id="tablePerson" class="table table-hover">
						<thead>
							<tr>
								<th>
									<?=$this->translate("ID");?>
									<a href="?field=id&<?=((isset($_GET['field']) && $_GET['field']=='id') && $_GET['orderby'] == 'desc')?'orderby=asc':'orderby=desc';?>">
										<i class="pull-right fa fa-arrows-v"></i>
									</a>
								</th>
								<th>
									<?=$this->translate("Nome");?>
									<a href="?field=name&<?=((isset($_GET['field']) && $_GET['field']=='nome') && $_GET['orderby'] == 'desc')?'orderby=asc':'orderby=desc';?>">
										<i class="pull-right fa fa-arrows-v"></i>
									</a>
								</th>
								<th>
									<?=$this->translate("Email");?>
									<a href="?field=email&<?=((isset($_GET['field']) && $_GET['field']=='email') && $_GET['orderby'] == 'desc')?'orderby=asc':'orderby=desc';?>">
										<i class="pull-right fa fa-arrows-v"></i>
									</a>
								</th>
								<th><?=$this->translate("Ação");?></th>
							</tr>
						</thead>
						<tbody>
							<?php
							if(isset($this->data))
							{
								foreach ($this->paginator as $entity) {
									$links['edit'] = $this->url('person/default', array('controller' => 'person', 'action' => 'edit', 'id' => $entity->getId()));
									$links['delete'] = $this->url('person/default', array('controller' => 'person', 'action' => 'delete', 'id' => $entity->getId()));
									$links['active'] = $this->url('person/default', array('controller' => 'person', 'action' => 'active', 'id' => $entity->getId()));
									$links['deactive'] = $this->url('person/default', array('controller' => 'person', 'action' => 'deactive', 'id' => $entity->getId()));
									$links['profile'] = $this->url('person/default', array('controller' => 'person', 'action' => 'profile', 'id' => $entity->getId()));
									$links['view'] = $this->url('person/default', array('controller' => 'person', 'action' => 'view', 'id' => $entity->getId()));
									?>
									<tr>
										<td>
											<?php echo $entity->getId(); ?>
										</td>
										<td><?php echo($entity->getName()); ?></td>
										<td><?php echo $entity->getEmail(); ?></td>
										<td>
											<a href="<?= $links['edit'] ?>">
												<button type="button" class="btn btn-info"><i
														class="fa fa-edit"></i> <?= $this->translate(""); ?>Editar
												</button>
											</a>
											<a class="deleteBT" href="<?= $links['delete'] ?>">
												<button type="button" class="btn btn-danger"><i
														class="fa fa-trash"></i> <?= $this->translate(""); ?>Deletar
												</button>
											</a>
										</td>
									</tr>
									<?php
								}
							}
							?>
						</tbody>
					</table>
                </div>
                <div class="box-footer clearfix">                
                	<?=$this->paginationControl($this->paginator,'Sliding','partials/paginator'); ?>
                </div>
              </div>
          </div>   	
    </div>
</div>
<script>
$(document).ready(function(){
    $(".deleteBT").click(function(){
    	var url = $(this).attr('href');
    	result = bootbox.dialog({
    	  message: <?=$this->translate("Deseja mesmo excluir esse registro?");?>,
    	  title: <?=$this->translate("Atenção!");?>,
    	  buttons: {	    
    	    danger: {
    	      label: <?=$this->translate("Não");?>,
    	      className: "btn-danger",
    	      callback: function() {	    	 
    	      }
    	    },
    	    success: {
    	      label: <?=$this->translate("Sim");?>,
    	      className: "btn-success",
    	      callback: function() {
    	        window.location.href = url;
    	        return false
    	      }
    	    },	    
    	  }
    	});
    	return false;	
    });
});
</script>