<?php
use Zend\Form\Form;
$form = $this->form;
$return = $this->url('person/default',array('controller'=>'person'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
        	<br />
        	<div class="box box-primary">
                <div class="box-header with-border">
                	<h3 class="box-title"><i class="fa fa-user-plus"></i> <?=$this->translate("Novo usuário");?></h3>
                </div><!-- /.box-header -->
                <!-- form start -->
                <form method="POST" role="form" id="person" action="<?=$this->url('person/default',array('controller'=>'person','action'=>'new'))?>">
                    <input type='hidden' name="adminForm" value='1'>
                    <div class="box-body">
                    	<div class="row">
                        	<div class="col-md-4">
                            	<div class="form-group">
                                    <label for="InputName"><?=$this->translate("Nome:");?></label>
                                    <?=$this->formelement(
                                                $form->get('name')
                                                    ->setAttribute("class","form-control")
                                                    ->setAttribute("id","InputName")
                                                    ->setAttribute("type","text")
                                            );?>
                                </div>
                        	</div>
                    	</div>
                	</div>
                	<div class="box-footer">  
                    	<?=$this->formelement($form->get('security'))?>     
                    	<?=$this->formelement($form->get('id'))?>     
                    	<button type="submit" name="submit" class="btn btn-app" >
                        	<i class="fa fa-save"></i> <?=$this->translate("Salvar");?>
                        </button>
                        <button type="reset" name="submit" class="btn btn-app" >
                        	<i class="fa fa-eraser"></i> <?=$this->translate("Limpar");?>
                        </button>
                        <a class="btn btn-app"  href="<?=$return?>">
                        	<i class="fa fa-arrow-circle-o-left"></i> <?=$this->translate("Retornar");?>
                        </a>
                    </div>
            	</form>
        	</div>
		</div>
	</div>
</div>