<?php 
use Register\Entity\Person;
use Register\Entity\Profile;
$return = $this->url('person/default',array('controller'=>'person'));

/**
 * @var \Register\Entity\PersonProfile[] $hasProfiles
 */
$person = $this->person;
$profiles = $this->profiles;
$hasProfiles = $this->personProfiles;
$time = time($person->getCreatedAt());
$data = date('d/m/Y',$time);

$arr_profiles = array();
if(!empty($hasProfiles)){
    foreach($hasProfiles as $hasProfile){
		$arr_profiles[] = $hasProfile->getProfile();
    }
};

?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Seleção de Perfis</li>
            </ol>
            <?php $this->getAdminFlashMessenger();?>
        </div>
        <form role="form" method="POST" action="<?=$this->url('person/default',array('controller'=>'person','action'=>'profile','id'=>$person->getId()));?>">
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4 class="title">
                                Seleção de Perfis
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th><?=$this->translate("Nome");?></th>
                                    <th><?=$this->translate("E-mail");?></th>
                                    <th><?=$this->translate("Membro Desde");?></th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td><?=$person->getName()?></td>
                                    <td><?=$person->getEmail()?></td>
                                    <td><?=$data?></td>
                                </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-12">
                            <label><?=$this->translate("Perfis");?></label>
                            <?php
                            if(isset($profiles)) {
                                foreach ($profiles as $profile) {
                                    ?>
                                    <div class="form-check">
                                        <input class="form-check-input" name="profiles[]" <?=(in_array($profile,$arr_profiles)) ? 'checked' : ''; ?> type="checkbox" value="<?= $profile->getId(); ?>">
                                        <label>
                                            <?= $profile->getName(); ?>
                                        </label>
                                    </div>
                                    <?php
                                }
                            }
                            ?>
                            <br/>
                        </div>
                    </div>
                    <div>
                        <button type="submit" name="submit" class="btn btn-success" >
                            <i class="fa fa-save"></i> <?=$this->translate("Salvar");?>
                        </button>
                        <button type="reset" name="submit" class="btn btn-danger" >
                            <i class="fa fa-eraser"></i> <?=$this->translate("Limpar");?>
                        </button>
                        <a class="btn btn-info"  href="<?=$return?>">
                            <i class="fa fa-arrow-circle-o-left"></i> <?=$this->translate("Retornar");?>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>
