<?php

$db_person          = $this->db_person;
$db_roles           = $this->db_roles;
$db_person_roles = $this->db_person_roles;

$arr_roles = array();
if(!empty($db_person_roles))
{
    foreach($db_person_roles as $db_person_role)
    {
        $arr_roles[] = $db_person_role->getRole()->getId();
    }
}

$return = $this->url(
    'person/default',
    array(
        'controller'=>'person'
    )
);

$action = $this->url(
    'person/default',
    array(
        'controller'    =>  'person',
        'action'        =>  'profile',
        'id'            =>  $db_person->getId()
    )
);
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active">Seleção de Perfis</li>
            </ol>
            <?php $this->getAdminFlashMessenger();?>
        </div>
        <form role="form" method="POST" action="<?=$action?>">
            <div class="col-md-12">
                <div class="card">
                    <div class="header">
                        <div class="row">
                            <div class="col-md-12">
                                <h4 style="margin-top: 0; text-transform: uppercase" class="text-info"><strong><?=$db_person->getName()?></strong></h4>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-8">
                                <h5 class="title">
                                    Seleção de Perfis
                                </h5>
                            </div>
                        </div>
                    </div>
                    <div class="content">

                        <div class="row">
                            <div class="col-md-12">
                                <label><?=$this->translate("Perfis");?></label>
                                <?php
                                if(!empty($db_roles)) {
                                    foreach ($db_roles as $db_role) {
                                        ?>
                                        <div class="form-check">
                                            <input class="form-check-input"
                                                name="roles[]"
                                                <?=(in_array($db_role->getId(),$arr_roles)) ? 'checked' : ''; ?>
                                                type="checkbox"
                                                value="<?= $db_role->getId(); ?>">
                                            <label>
                                                <?= $db_role->getName(); ?>
                                            </label>
                                        </div>
                                        <?php
                                    }
                                }
                                ?>
                                <br/>
                            </div>
                        </div>
                        <div>
                            <button type="submit" name="submit" class="btn btn-success" >
                                <i class="fa fa-save"></i> <?=$this->translate("Salvar");?>
                            </button>
                            <button type="reset" name="submit" class="btn btn-danger" >
                                <i class="fa fa-eraser"></i> <?=$this->translate("Limpar");?>
                            </button>
                            <a class="btn btn-info"  href="<?=$return?>">
                                <i class="fa fa-arrow-circle-o-left"></i> <?=$this->translate("Retornar");?>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
