<?php
namespace Site\Service;

use Base\Service\AbstractService;

class Banner extends AbstractService{
    public function __construct(\Doctrine\ORM\EntityManager $em) {
        parent::__construct($em);
        $this->entity = 'Site\Entity\Banner';
    }

    public function insert(array $data)
    {
        $entity = parent::insert($data); // TODO: Change the autogenerated stub
        
        $this->insertFile($entity,'image','public/img/banner/','banner');
    }

    public function update(array $data)
    {
        $entity = parent::update($data);        
        $this->insertFile($entity,'image','public/img/banner/','banner');
    }
}


























?>