<?php
use Zend\Form\Form;
/**
 *
 * @var Form $form
 */
$form = $this->form;
$form->setAttribute('action',$this->url('admin/defaults',array('controller'=>'profile', 'action'=>'edit')));
$form->prepare();

$return = $this->url('admin/defaults',array('controller'=>'profile'));
?>
<div class="row">
    <div class="col-md-12">
        <div class="col-md-12">
        	<br />
        	<div class="box box-primary">
                <div class="box-header with-border">
                	<h3 class="box-title"><i class="fa fa-user-plus"></i> <?=$this->translate("Novo perfil");?></h3>
                </div>
                <?php echo $this->form()->openTag($form);?>
                    <div class="box-body">
                    	<div class="row">                        	
                        	<div class="col-md-12">                        		
                            	<div class="form-group">
                                    <label for="InputName"><?=$this->translate("Nome *");?></label>
                                    <?=$this->formelement(
                                        $form->get('name')
                                            ->setAttribute("class","form-control")
                                            ->setAttribute("id","InputName")
                                            ->setAttribute("type","text")
                                            ->setAttribute("required","required")
                                    );?>
                                </div>
                        	</div>                        
                    	</div>                    
                	</div>
                    <div class="box-footer">                      	
                    	<?=$this->formelement($form->get('id'))?>     
                    	<button type="submit" name="submit" class="btn btn-app" >
                        	<i class="fa fa-save"></i> <?=$this->translate("Salvar");?>
                        </button>
                        <button type="reset" name="submit" class="btn btn-app" >
                        	<i class="fa fa-eraser"></i> <?=$this->translate("Limpar");?>
                        </button>
                        <a class="btn btn-app"  href="<?=$return?>">
                        	<i class="fa fa-arrow-circle-o-left"></i> <?=$this->translate("Retornar");?>
                        </a>
                    </div>
                <?php 
                echo $this->form()->closeTag();
                ?>
            </div>        
        </div>
    </div>
</div>
