<?php
namespace Admin\Controller;

use Base\Controller\CrudController;

class LayoutController extends CrudController{
    public function __construct() {
        $this->title        = "Configuração de Layout";
        $this->table        = 'Layout';
        $this->entity       = 'Admin\Entity\\'.$this->table ;
        $this->service      = 'Admin\Service\\'.$this->table ;
        $this->form         = 'Admin\Form\\'.$this->table ;
        $this->controller   = "layout";
        $this->route        = "layout/defaults";

        $this->_listView = array(
            'title' => $this->title,
            'icon' => 'fa-fw fa fa-image',
            'route' => $this->route,
            'controller' => $this->controller,
            'actions' => array(
                'enable' =>true,
                'defaults' => array(
                    'new' => array(
                        'enable' => false,
                        'class' => 'btn btn-succes',
                        'icon' => 'fa fa-plus'
                    ),
                    'edit' => array(
                        'enable' => true,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-edit'
                    ),
                    'delete' => array(
                        'enable' => false,
                        'class' => 'btn btn-danger decision',
                        'icon' => 'fa fa-trash'
                    ),
                    'view' => array(
                        'enable' => false,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-eye'
                    ),
                ),
            ),
            'fields' => array(
                'id'=>array(
                    'label' => 'Id',
                    'list' => true,
                ),
                'title'=>array(
                    'label' => $this->translate('Título'),
                    'list' => true,
                ),
                'activeStr'=>array(
                    'label' => $this->translate('Ativo'),
                    'list' => true,
                )
            ),
        );
    }

    public function editAction($request = null, $form = null, $redirect = null)
    {
        $request = $this->getRequest();
        if($request->isPost()) {
            $db_layouts = $this->getEm()->getRepository('Admin\Entity\Layout')->findAll();
            if (!empty($db_layouts)) {
                foreach ($db_layouts as $db_layout) {
                    $db_layout->setActive(0);
                    $this->getEm()->persist($db_layout);
                }

                $this->getEm()->flush();
            }
        }
        return parent::editAction($request, $form, $redirect); // TODO: Change the autogenerated stub
    }

}