<section class="content-header">
    <h1>
        <?=$this->data_page['title']?> - <small>Cadastre, atulize, recorte imagens</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('admin');?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Imagens</li>
    </ol>
</section>
<br /><br />
<?php

$em = $this->em;
//Definido em Register/config/module.config.php
//template_map => 'image-interface' => __DIR__ . '/../view/partials/image-interface.phtml'
echo $this->partial('image-interface',array(
    'data_page' => $this->data_page,
    'entity' => $this->entity,
    'controller' => $this->controller,
    'em' => $em,
    'id' => $this->id
));
?>