<?php
/**
 * @var \App\Entity\App $db_app
 */
$db_app = $this->app;
$em = $this->em;

$path = str_replace(' ','',$db_app->getIntegration()->getName()).'\Form\Config';
echo $this->partial('config-interface',array(
    'title' => 'Data Frete',
    'form'  => new $path($this->em),
    'app' => $db_app
));

function strToFriendlyUrl($str){
    $str = mb_strtolower(utf8_decode($str));
    $i=1;
    $str = strtr($str, utf8_decode('àáâãäåæçèéêëìíîïñòóôõöøùúûýýÿ'), 'aaaaaaaceeeeiiiinoooooouuuyyy');
    $str = preg_replace("/([^a-z0-9])/",'-',utf8_encode($str));
    while($i>0) $str = str_replace('--','-',$str,$i);
    if (substr($str, -1) == '-') $str = substr($str, 0, -1);
    return $str;
}

?>