<?php
echo $this->doctype();
?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="Place One" />
        <meta name="keywords" content="Place One" />
        <meta name="author" content="freehtml5.co" />

        <meta property="og:title" content=""/>
        <meta property="og:image" content=""/>
        <meta property="og:url" content=""/>
        <meta property="og:site_name" content=""/>
        <meta property="og:description" content=""/>
        <meta name="twitter:title" content="" />
        <meta name="twitter:image" content="" />
        <meta name="twitter:url" content="" />
        <meta name="twitter:card" content="" />

        <link href="https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,700,800" rel="stylesheet">

        <?php

		echo $this->headTitle('Site '. $this->translate('- Site Base'))
			->setSeparator(' - ')->setAutoEscape(false);

		echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge');

		echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
            ->prependStylesheet($this->basePath('css/site/styles.css'))
            ->prependStylesheet($this->basePath('css/site/style.css'))
            ->prependStylesheet($this->basePath('css/site/owl.theme.default.min.css'))
            ->prependStylesheet($this->basePath('css/site/owl.carousel.min.css'))
            ->prependStylesheet($this->basePath('css/site/magnific-popup.css'))
            ->prependStylesheet($this->basePath('css/site/bootstrap.css'))
            ->prependStylesheet($this->basePath('css/site/icomoon.css'))
            ->prependStylesheet($this->basePath('css/site/animate.css'));

		echo $this->headScript()
            ->prependFile($this->basePath('js/admin/geral.js'))
			->prependFile($this->basePath('js/site/geral.js'))
            ->prependFile($this->basePath('js/site/main.js'))
            ->prependFile($this->basePath('js/site/magnific-popup-options.js'))
            ->prependFile($this->basePath('js/site/jquery.magnific-popup.min.js'))
            ->prependFile($this->basePath('js/site/jquery.countTo.js'))
            ->prependFile($this->basePath('js/site/owl.carousel.min.js'))
            ->prependFile($this->basePath('js/site/jquery.stellar.min.js'))
            ->prependFile($this->basePath('js/site/jquery.waypoints.min.js'))
            ->prependFile($this->basePath('js/site/bootstrap.min.js'))
            ->prependFile($this->basePath('js/site/jquery.easing.1.3.js'))
            ->prependFile($this->basePath('js/site/jquery.min.js'))
            ->prependFile($this->basePath('js/site/respond.min.js'))
            ->prependFile($this->basePath('js/site/modernizr-2.6.2.min.js'));
		
		global $em;
		$em = $this->getEm();
        $logo       = $this->getConfiguration('LOGO');
        $db_person  = $this->personIdentity('Person');
        $path       = $_SERVER['REQUEST_URI'];
		?>
    </head>
    <body>
        <?php echo $this->content;?>
	</body>
</html>
