<div class="col-xs-12 col-sm-12 col-md-7 col-lg-8 hidden-xs hidden-sm">
    <h1 class="txt-color-red login-header-big"><?=$this->getText('TEXTO_AUTH')->getTitle();?></h1>
    <div class="hero">

        <div class="pull-left login-desc-box-l">
            <p class="text-justify"><?=strip_tags($this->getText('TEXTO_AUTH')->getText());?></p>
            <div class="login-app-icons">
                <a href="<?=$this->url('home');?>" class="btn btn-danger btn-sm">Ir para o Site</a>
                <?php
                if($_SERVER['REDIRECT_URL'] == '/auth/lostpassword')
                {
                    ?>
                    <a href="<?=$this->url('person-auth');?>" class="btn btn-danger btn-sm">Ir para área de Login</a>
                    <?php
                }
                ?>
            </div>
        </div>
        <img src="<?=$this->getConfiguration('IMAGE_AUTH');?>" class="pull-right display-image" alt="" style="width:210px">
    </div>
</div>