<?php
namespace Register\Service;

use Base\Service\AbstractService;

class Address extends AbstractService{
    public function __construct(\Doctrine\ORM\EntityManager $em) {
        parent::__construct($em);
        $this->entity = 'Register\Entity\Address';
    }

    public function insert(array $data)
    {
        $entity = parent::insert($data); // TODO: Change the autogenerated stub
        return $entity;
    }

    public function update(array $data)
    {
        $entity = parent::update($data);
        return $entity;
    }
}


























?>