<?php

namespace Register\Service;

use Base\Service\AbstractService;

use Zend\Mail\Transport\Smtp as SmtpTransport;
use Zend\Mail\Transport\SmtpOptions;
use Base\Mail\Mail;

class BankAccount extends AbstractService{

    protected $em;

    public function __construct(\Doctrine\ORM\EntityManager $em) {
        parent::__construct($em);
        $this->entity = 'Register\Entity\BankAccount';
    }

    public function insert(array $data)
    {
        $data['person'] = $this->em->getRepository('Register\Entity\Person')->findOneById($data['person']);

        $entity = parent::insert($data); // TODO: Change the autogenerated stub

        return $entity;
    }

    public function update(array $data)
    {
        $data['person'] = $this->em->getRepository('Register\Entity\Person')->findOneById($data['person']);

        $entity = parent::update($data);
        $entity = $this->em->getRepository('Register\Entity\BankAccount')->findOneById($entity->getId());

        return $entity;
    }
}

























?>


























?>