<?php
$form = $this->form;
$form->setAttribute('action', $this->url('person-auth'));
$form->prepare();

?>
<div class="col-md-12 flashMessages">
    <?php
    $flash  =  $this->flashMessenger ();
    echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' ));
    echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' ));
    echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' ));
    echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));

    ?>
</div>
<div id="content" class="container">
    <div class="row">
        <?=$this->partial('partials/text-auth');?>
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">
                <?php
                if(isset($this->login) && is_object($this->login)) {
                    ?>
                    <form action="index.html" id="login-form" class="smart-form client-form">
                        <header>
                            <?=$this->translate('Bem vindo <strong>'.$this->login->getName().'</strong>');?>
                        </header>
                        <fieldset>
                            <section>
                                <div align="center">
                                    <a  href="/admin" class="btn-lg btn btn-success">
                                        <i class="fa fa-lock"></i> <?=$this->translate("Área Restrita");?>
                                    </a>
                                </div>
                            </section>
                            <section>
                                <div align="center">
                                    <a href="/auth/logout" class="btn-lg btn btn-warning">
                                        <i class="fa fa-sign-out"></i> Deslogar
                                    </a>
                                </div>
                            </section>
                        </fieldset>
                    <?php

                }else{

                    ?>
                        <form id="loginForm" method="post" action="" class="smart-form client-form">
                        <header>
                            <?=$this->translate("Já possuo uma conta");?>
                        </header>
                        <fieldset>
                            <?php
                            if($this->error){
                                ?>
                                <section>
                                    <div class="alert alert-danger fade in">
                                        <button class="close" data-dismiss="alert">
                                            ×
                                        </button>
                                        <i class="fa-fw fa fa-times"></i>
                                        <strong>Erro!</strong> <?=$this->translate("Usuário ou senha inválidos.");?>
                                    </div>
                                </section>
                                <?php
                            }
                            ?>

                            <section>
                                <label class="label"><?=$this->translate("Usuário / E-mail");?></label>
                                <label class="input"> <i class="icon-append fa fa-user"></i>
                                    <input name="email" type="email" required>
                                    <b class="tooltip tooltip-top-right">
                                        <i class="fa fa-user txt-color-teal"></i> Por favor insira seu e-mail
                                    </b>
                                </label>
                            </section>

                            <section>
                                <label class="label">Senha</label>
                                <label class="input"> <i class="icon-append fa fa-lock"></i>
                                    <input name="password" type="password" required>
                                    <b class="tooltip tooltip-top-right">
                                        <i class="fa fa-lock txt-color-teal"></i> Entra com sua senha
                                    </b>
                                </label>
                                <div class="note">
                                    <a href="/auth/lostpassword"><?=$this->translate("(Perdeu a senha?)");?></a>
                                </div>
                            </section>

                            <section>
                                <label class="checkbox">
                                    <input type="checkbox" name="remember" checked="">
                                    <i></i>Permanecer Logado</label>
                            </section>
                        </fieldset>
                        <footer>
                            <button onclick="$('#loginForm').submit();" type="submit" class="btn btn-primary">
                                <?=$this->translate("Logar");?>
                            </button>
                        </footer>
                    </form>
                <?}?>
            </div>
        </div>
    </div>
</div>
