<?php
$form = $this->form;
$form->setAttribute('action', $this->url('lostpassword'));
$form->prepare();
?>
<div class="col-md-12 flashMessages">
    <?php
    $flash  =  $this->flashMessenger ();
    echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' ));
    echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' ));
    echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' ));
    echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));
    ?>
</div>
<div id="content" class="container">
    <div class="row">
        <?=$this->partial('partials/text-auth');?>
        <div class="col-xs-12 col-sm-12 col-md-5 col-lg-4">
            <div class="well no-padding">
                <form autocomplete="off" id="Login" method="post" class="smart-form client-form">
                    <?php
                    if(isset($_GET['redirect']))
                    {
                        ?>
                        <input type="hidden" name="redirect" value="<?=$_GET['redirect']?>">
                        <?php
                    }
                    ?>
                    <header>
                        <?=$this->translate("Recuperar a senha")?>
                    </header>
                    <fieldset>
                        <section>
                            <label class="label"><?=$this->translate("Usuário / E-mail");?></label>
                            <label class="input"> <i class="icon-append fa fa-envelope-o"></i>
                                <input autocomplete="off" name="email" type="email" required>
                                <b class="tooltip tooltip-top-right">
                                    <i class="fa fa-user txt-color-teal"></i> Por favor insira seu e-mail
                                </b>
                            </label>
                        </section>
                    </fieldset>
                    <footer>
                        <input type="submit" value="<?=$this->translate("Enviar")?>" class="btn btn-primary pull-right push-bottom" data-loading-text="Loading...">
                    </footer>
                </form>
            </div>
        </div>
    </div>
</div>




