<?php
$form = $this->form;
$form->setAttribute('action', $this->url('lostpassword'));
$form->prepare();
?>
<div role="main" class="main">
    <section class="page-top">
    	<div class="container">    		    		
    		<div class="row">
    			<div class="col-md-8">
        			<div class="row">
            			<div class="col-md-12">
            				<ul class="breadcrumb">
            					<li><a target="_parent" href="/home">Home</a></li>
            					<li><a target="_parent" href="<?=$this->url('person-auth',array('controller'=>'index'))?>"><?=$this->translate("Login")?></a></li>
            					<li class="active"><?=$this->translate("Recuperar a senha")?></li>
            				</ul>
            			</div>
            		</div>
            		<div class="row">
            			<div class="col-md-12">
            				<h1><?=$this->translate("Recuperar a senha")?></h1>
            			</div>
            		</div>
    			</div>
    			<div class="col-md-4">
    				<div align="center">
    				</div>
				</div>
    		</div>
    	</div>
    </section>
     <div class="container">
    	<div class="row">
            <div class="col-md-12 flashMessages">
                <?php 
                 $flash  =  $this->flashMessenger (); 
                 echo  $flash -> render ( 'error' ,    array ( 'alert' ,  'alert-dismissible' ,  'alert-danger' )); 
                 echo  $flash -> render ( 'info' ,     array ( 'alert' ,  'alert-dismissible' ,  'alert-info' )); 
                 echo  $flash -> render ( 'default' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-warning' )); 
                 echo  $flash -> render ( 'success' ,  array ( 'alert' ,  'alert-dismissible' ,  'alert-success' ));
                 ?>
            </div>
    	</div>
    </div>
    <br />
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<br />
				<div class="row featured-boxes login">
					<div class="col-sm-6 col-md-offset-3">
						<div class="featured-box featured-box-secundary default info-content">
							<div class="box-content">
								<h4><?=$this->translate("Insira seu e-mail")?></h4>
								<?php 
								echo $this->form()->openTag($form);											
								?>								
    								<div class="row">
    									<div class="form-group">
    										<div class="col-md-12">
    											<label><?=$this->translate("E-mail")?></label>
    											<input name="email" type="email" value="" class="form-control input-lg">
    										</div>
    									</div>
    								</div>								
    								<div class="row">
    									<div class="col-md-12">										
    										<input type="submit" value="<?=$this->translate("Enviar")?>" class="btn btn-primary pull-right push-bottom" data-loading-text="Loading...">
    									</div>
    								</div>
								<?php 									
								echo $this->form()->closeTag();
								?>								
							</div>
						</div>
					</div>					
				</div>
			</div>
		</div>
	</div>
</div>
