<?php
/**
 * @var \Activities\Entity\Activities $db_activity
 */
$db_activity = $this->activity;
$em = $this->em;
?>
<div role="main" class="main">
    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="row">
                        <div class="col-md-12">
                            <ul class="breadcrumb">
                                <li>
                                    <a target="_parent" href="<?=$this->url('home')?>">
                                        Home
                                    </a>
                                </li>
                                <li>
                                    <a target="_parent" href="<?=$this->url('activities-site')?>">
                                        Atividades
                                    </a>
                                </li>
                                <li>
                                    <?=$db_activity->getName();?>
                                </li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1><?=$db_activity->getName();?></h1>
                </div>
                <div class="col-md-9">
                    <p class="text-justify"><?=$db_activity->getText();?></p>
                </div>
                <div class="col-md-3">
                    <?php
                    $db_activities = $em->getRepository('Activities\Entity\Activities')->getForMenu($db_activity->getId());

                    if(!empty($db_activities))
                    {
                        ?>
                        <div class="price-box">
                            <h3 >Atividades</h3>
                            <ul class="classes">
                                <?php
                                $count = 0;
                                foreach($db_activities as $db_act)
                                {
                                    $class = ($count % 2)?'color':'';
                                    $url_act = $this->url('activities-site/defaults', array(
                                        'action' => 'activity',
                                        'id' => $db_act->getId()
                                    ));
                                    ?>
                                    <li class="<?=$class?>">
                                        <a href="<?=$url_act?>">
                                            <b><?=$db_act->getName()?></b>
                                        </a>
                                    </li>
                                    <?php
                                    $count++;
                                }
                                ?>
                            </ul>
                            <a href="<?=$this->url('teacher-site');?>" class="btn btn-select-plan btn-sm">Ver Todos</a>
                        </div>
                        <?php
                    }
                    ?>
                </div>
            </div>
        </div>
    </section>
</div>
<br/>
<br/>
