<?php
/**
 * @var Site\Entity\Text $db_text
 */
$db_text = $this->getText('CONTATO');

?>
<br />
<div class="col-md-12 flashMessages">
    <?php $this->getAdminFlashMessenger();?>
</div>
<br />
<header id="fh5co-header" class="fh5co-cover fh5co-cover-sm" role="banner" style="background-image:url('/img/img_bg_2.jpg');" data-stellar-background-ratio="0.5">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center">
                <div class="display-t">
                    <div class="display-tc animate-box" data-animate-effect="fadeIn">
                        <h1><?=$db_text->getTitle()?></h1>
                        <h2><?=$db_text->getText()?></h2>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<div id="map" class="fh5co-map"></div>
<div id="fh5co-contact">
    <div>
        <div class="row">
            <div class="col-md-5 col-md-offset-1 animate-box">
                <div class="fh5co-contact-info">
                    <h3>Informações de Contato</h3>
                    <ul>
                        <li class="address">
                            <?=$this->getConfiguration('ENDERECO');?>
                        </li>
                        <li class="phone">
                            <?php
                            $arr = array(
                                '(',')',' ','-'
                            )
                            ?>
                            <a href="tel://<?=str_replace($arr,'',$this->getConfiguration('TELEFONEEMPRESA'));?>">
                                <?=$this->getConfiguration('TELEFONEEMPRESA');?>
                            </a>
                        </li>
                        <li class="email">
                            <a href="mailto:<?=$this->getConfiguration('EMAILEMPRESA');?>">
                                <?=$this->getConfiguration('EMAILEMPRESA');?>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md-5 animate-box">
                <h3>Envie-nos uma Mensagem</h3>
                <form method="post" name="contact-form" id="contact-form" action="<?=$this->url('home-contact');?>">
                    <div class="row form-group">
                        <div class="col-md-6">
                            <input type="text" name="fname" id="fname" class="form-control" placeholder="Seu Primeiro Nome" required>
                        </div>
                        <div class="col-md-6">
                            <input type="text" name="lname" id="lname" class="form-control" placeholder="Seu Sobrenome" required>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <input type="email" name="email" id="email" class="form-control" placeholder="Seu E-mail" required>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <input type="text" name="phone" id="phone" class="form-control" placeholder="Telefone" required>
                        </div>
                    </div>

                    <div class="row form-group">
                        <div class="col-md-12">
                            <textarea name="message" id="message" cols="30" rows="10" class="form-control" placeholder="Digite alguma coisa para nós" required></textarea>
                        </div>
                    </div>
                    <div class="row form-group">
                        <div class="col-md-12">
                            <div class="g-recaptcha" data-sitekey="6LdZUGEUAAAAAGCxHhiLL5lqttcG7ah-YUMghR9z"></div>
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Enviar" class="btn btn-primary">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
