<?php
global $em;
$em = $this->getEm();
?>
<?=$this->partial('partial/banner.phtml',array('em' => $em));?>
<?=$this->partial('partial/activities.phtml',array('em' => $em));?>
<?=$this->partial('partial/teachers.phtml',array('em' => $em,'limit' => 4,'rand' => true));?>
<?=$this->partial('partial/calendar.phtml',array('em' => $em));?>
<?=$this->partial('partial/gymgallery.phtml',array('em' => $em,'page' => false));?>
<?=$this->partial('partial/testimony.phtml',array('em' => $em));?>