<div role="main" class="main">
    <section class="page-top">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <ul class="breadcrumb">
                        <li><a href="<?=$this->url('home');?>">Home</a></li>
                        <li class="active">Erro de Acesso</li>
                    </ul>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <h1>Erro de Acesso</h1>
                </div>
            </div>
        </div>
    </section>
    <div class="container">
        <section class="page-not-found">
            <div class="row">
                <div class="col-md-6">
                    <div class="page-not-found-main text-center">
                        <h1>Desculpe <i class="fa fa-frown-o"></i></h1>
                        <p>Você não tem permissão para acessar a página solicitada</p>
                    </div>
                </div>
                <div class="col-md-3">
                    <h4>Aqui está alguns links úteis</h4>
                    <ul class="nav nav-list primary">
                        <li><a href="<?=$this->url('admin');?>">Área administrativa</a></li>
                        <li><a href="<?=$this->url('home');?>">Home</a></li>
                        <li><a href="<?=$this->url('person-auth');?>">Cadastro/Login</a></li>
                        <li><a href="<?=$this->url('home',array('controller' => 'index','action' => 'how-it-works'));?>">Como Funciona</a></li>
                        <li><a href="<?=$this->url('home',array('controller' => 'index','action' => 'faq'));?>">Perguntas Frequentes</a></li>
                    </ul>
                </div>
            </div>
        </section>
    </div>
</div>