<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */

return [
    'Zend\\Db',
    'Zend\\Filter',
    'Zend\\InputFilter',
    'Zend\\Paginator',
    'Zend\\Validator',
    'ZF\\Apigility',
    'ZF\\Apigility\\Provider',
    'AssetManager',
    'ZF\\Apigility\\Documentation',
    'ZF\\ApiProblem',
    'ZF\\Configuration',
    'ZF\\MvcAuth',
    'ZF\\OAuth2',
    'ZF\\Hal',
    'ZF\\ContentNegotiation',
    'ZF\\ContentValidation',
    'ZF\\Rest',
    'ZF\\Rpc',
    'ZF\\Versioning',
    'ZF\\DevelopmentMode',
    'DoctrineModule',
    'DoctrineORMModule',
    'Phpro\\DoctrineHydrationModule',
    'ZF\\Apigility\\Doctrine\\Server',
    'ZF\Doctrine\QueryBuilder',
    'Application',
    'Base',
    'Site',
    'Register',
    'Catalog',
    'Transaction',
    'App',
    'Financial',
    'Relation',
    'DataFrete',
    'Acl',
    'api',
    'Admin',
];
