<?php
if(isset($this->route) && isset($this->controller) && isset($this->action) && isset($this->id))
{
    $action = $this->url($this->route,array(
        'controller' => $this->controller,
        'action' => $this->action,
        'id' => $this->id
    ));
}

/** DECLARAÇÕES **/
$person = $this->personIdentity('Person');
$form = $this->form;
$chave = ($this->controller == 'people')?'person':$this->controller;

/** new ou edit **/
$type = $this->type;

/** adicionar registro ou editar registro **/
$acao = $this->acao;

$form->setAttribute('action', $this->url($this->route, array(
    'controller' => $this->controller,
    'action' => $type
)))->prepare();

/**
 * @var \Base\Controller\BaseFunctions $functions
 */
$functions = new \Base\Controller\BaseFunctions();
if($this->fk != null && $this->fk_id != null)
{
    $link['return'] = $this->url($functions->strToFriendlyUrl($controller).'-join',array('fk' => $fk,'fk_id' => $fk_id));
}

if($fk != null && $fk_id != null) {
    $form->setAttribute('action', $this->url($functions->strToFriendlyUrl($controller) . '-join-' . $type, array('fk' => $fk, 'fk_id' => $fk_id, 'id' => $this->id)));
}

if(isset($action)){
    $form->setAttribute('action',$action);
}

if($link['return'] == '') {
    $link['return'] = $this->url();
}
?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="<?=$this->url('admin')?>"><i class="fa fa-dashboard"></i> Home</a></li>
                <?php
                if(isset($_GET['profile']))
                {
                    $url = $this->url($_GET['profile'].'/default',array(
                        'controller' => 'person',
                        'action' => $_GET['profile']
                    ));
                    ?>
                    <li>
                        <a href="<?=$url?>">
                            <i class="<?=$this->icon?>"></i> <?=$this->title?>
                        </a>
                    </li>
                    <?php
                }else{
                    ?>
                    <li><a href="<?=$this->url($this->_listView['route']);?>"><i class="<?=$this->icon?>"></i> <?=$this->title?></a></li>
                    <?php
                }
                ?>

                <li class="active"><?=$acao?></li>
            </ol>
            <?php $this->getAdminFlashMessenger();?>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <div class="row">
                        <div class="col-md-12">
                            <h4 class="title">
                                <?=$this->title?> - <small><?=$this->translate($acao)?></small>
                            </h4>
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <?=$this->form()->openTag($form);?>
                            <div>
                                <?php
                                $hidden = array(
                                    'hidden' => 1,
                                    'submit' => 1
                                );

                                foreach ($form as $element) {

                                    //SE FOR JOIN
                                    if($this->fk != null && $this->fk_id != null && $element->getName() == $this->fk)
                                    {
                                        $element->setAttribute('value',$this->fk_id);
                                        $element->setAttribute('readonly','readonly');
                                    }

                                    $element->setAttribute('form',$form->getName());

                                    $type = $element->getAttributes()['type'];
                                    switch ($type){
                                        case ($element instanceof \Zend\Form\Element\Textarea):
                                            $column = "col-md-12";
                                            break;
                                        case "radio":
                                            $column = "col-md-12";
                                            break;
                                        default:
                                            $column = "col-md-4";
                                    }

                                    $column .= ' field';
                                    $id = 'input'.$element->getName();
                                    $style = ($hidden[$type])?'display:none':'display:block';

                                    if($element->getName() == 'icon')
                                    {
                                        $column = "col-md-8";
                                    }
                                    ?>
                                    <div id="<?=$id?>" style="<?=$style?>" class="<?=$column?>">
                                        <div class="form-group">
                                            <?php
                                            $entity = $this->entity;

                                            if ($element->getLabel() != null) {
                                                echo "<label for='Input" . $element->getName() . "'>" . $element->getLabel() . "</label>";
                                            }

                                            $formElement = $form->get($element->getName());

                                            if ($type != 'checkbox' && $type != 'multi_checkbox')
                                            {
                                                $formElement->setAttribute("class", $formElement->getAttribute('class')." form-control ");
                                            } else {
                                                $formElement->setAttribute("class", "checkbox");
                                                $arr_values = explode(',',$formElement->getValue());
                                                $formElement->setValue($arr_values);
                                            }

                                            if ($type == 'radio') {
                                                $formElement->setAttribute("class", "radio ");
                                            }

                                            $formElement->setAttribute("id", "Input" . $element->getName())->setAttribute("type", $type);

                                            if($type == 'date') {
                                                echo '
                                                    <div class="input-group input-group-md">
                                                    ';

                                                echo $this->formelement($formElement);

                                                echo '
                                                        <span class="input-group-btn">
                                                            <button type="button" onclick="setToday(\''.$formElement->getAttribute('id').'\')" class="btn btn-info">Hoje</button>
                                                        </span>
                                                    </div>';
                                            }else{
                                                $classes = explode(' ',$formElement->getAttribute('class'));

                                                if(in_array('rich-text',$classes)){
                                                    $formElement->setAttribute('name',$formElement->getName());
                                                    echo $this->formelement($formElement);
                                                    echo '<div class="summernote" id="summernote_'.$formElement->getName().'" ></div>';
                                                }else if(isset($formElement->getattributes()['limit-text'])){
                                                    $tipo   = $formElement->getAttribute('type');
                                                    $limit  = $formElement->getattributes()['limit-text'];
                                                    $name   = $formElement->getAttribute('name');
                                                    $value  = $formElement->getValue();
                                                    $id     = $formElement->getAttribute('id');
                                                    ?>
                                                    <div id="limit-number-<?=$name?>"
                                                         class="limit-number bg-warning">
                                                        <?=$limit?>
                                                    </div>
                                                    <?php
                                                    if($tipo == 'textarea')
                                                    {
                                                        ?>
                                                        <textarea class="form-group <?=$formElement->getAttribute('class')?>"
                                                                  limit-text="<?=$limit?>"
                                                                  id="input-<?=$name?>"
                                                                  name="<?=$name?>" ><?=$value?></textarea>
                                                        <?php
                                                    }else{
                                                        ?>
                                                        <input  class="form-group <?=$formElement->getAttribute('class')?>"
                                                                imit-text="<?=$limit?>"
                                                                id="input-<?=$name?>"
                                                                type="<?=$tipo?>"
                                                                name="<?=$name?>"
                                                                value="<?=$value?>"
                                                        />
                                                        <?php
                                                    }
                                                }else{
                                                    echo $this->formelement($formElement);
                                                }
                                            }

                                            echo $this->formElementErrors($element);

                                            if($type == 'file') {
                                                $file = $this->getFile($this->controller, $element->getName(), $this->id);
                                                $tmp = explode('.',$file);
                                                $tmp = strtolower($tmp[count($tmp)-1]);

                                                if($file && $file != '/'){
                                                    $element->setAttribute('value',$file);?>
                                                    <script>
                                                        $("input[name=<?=$element->getName()?>]").removeAttr('required');
                                                    </script>
                                                <?
                                                if($tmp == 'png' || $tmp == 'jpg' || $tmp == 'jpeg'){
                                                ?>
                                                    <div class="col-md-12">
                                                        <center>
                                                            <a  target="_blank" href="<?= $file ?>">
                                                                <img style="height: 40px;margin-top: 5px" src="<?=$file?>"/>
                                                                <p>Maximizar</p>
                                                            </a>
                                                        </center>
                                                    </div>
                                                    <?
                                                }else{
                                                    ?>
                                                    <div class="col-md-12">
                                                        <a  target="_blank" href="<?= $file ?>">Baixar Arquivo</a>
                                                    </div>
                                                <?
                                                }
                                                }else{
                                                ?>
                                                    <div class="col-md-12">
                                                        <p class="text-red">Não há imagem cadastrada</p>
                                                    </div>
                                                    <?
                                                }
                                            }
                                            ?>
                                        </div>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <button type="submit" name="submit" class="btn btn-app">
                                        <i class="pe-7s-diskette"></i> Salvar
                                    </button>
                                    <a class="btn btn-app" href="<?=$link['return']?>">
                                        <i class="pe-7s-angle-left"></i> Retornar
                                    </a>
                                </div>
                            </div>
                            <?=$this->form()->closeTag();?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
