<html>
<head>
</head>
<body >
<div style="width:100%;background-color: #444;" align="center">
    <p>&nbsp;</p>
    <table   style="background-color: #fff" width="600">
        <thead>
        <tr>
            <th>
                <div style="width: 94%; padding: 3%; background-color:#132f3b;border-bottom: 3px solid #f87902;">
                    <h1 style="text-align:center;color:#fff;font-weight:bold"><?=$this->getConfiguration('LOGO')?></h1>
                </div>
            </th>
        </tr>
        </thead>
        <tbody >
        <tr >
            <td>
                <div style="padding: 5px">
                    <h4>
                        <strong>Envio de Comprovante</strong>
                    </h4>
                    <p>
                        O cliente <?=$this->nome?> enviou o comprovante de depósito, faça a verificação
                        necessária.
                        O valor de acordo com o plano assinado pelo cliente é de <?=$this->valor?>.<br />
                        Faça a ativação do plano se tudo estiver correto.
                    </p>
                    <p>
                        Acesse o plano para análise clicando <a href="<?=$this->rota?>">aqui</a>
                    </p>
                    <br/>
                </div>
            </td>
        </tr>
        </tbody>
        <tfoot>
        <tr>
            <td>
                <div style="width: 94%; padding: 3%; background-color:#132f3b;border-top: 3px solid #f87902;color: #fff">
                    <h4>
                        <?=$this->translate("Informa&ccedil;&otilde;es para contato");?>
                    </h4>
                    <strong>Tel: </strong> <?=$this->getConfiguration('TELEFONEEMPRESA')?> <?=$this->translate("ou");?> <?=$this->getConfiguration('CELULAREMPRESA')?>&nbsp;&nbsp;&nbsp;
                    <strong>Skype: </strong> <?=$this->getConfiguration('SKYPE')?><br/>
                    <strong>Email: </strong> <?=$this->getConfiguration('EMAILEMPRESA')?><br/>
                    <strong>Neteller: </strong> <?=$this->getConfiguration('NETELLER')?>
                </div>
            </td>
        </tr>
        </tfoot>
    </table>
    <p>&nbsp;</p>
</div>
</body>
</html>