<html>
	<head>
	
	</head>
	<body >
		<div style="width:100%;background-color: #444;" align="center">
			<p>&nbsp;</p>
    		<table   style="background-color: #fff" width="600">
				<thead>
				<tr>
					<th>
						<div style="width: 94%; padding: 3%; background-color:#132f3b;border-bottom: 3px solid #f87902;">
							<?=$this->getConfiguration('LOGO')?>
						</div>
					</th>
				</tr>
				</thead>
    			<tbody >
    				<tr >
    					<td>
    						<div style="padding: 5px">
    							<h4>
    								<strong><?=$this->translate("Ol&aacute; {$this->nome}");?></strong>
    							</h4>
    							<br />                               
                                
                                <p>
									<?=$this->translate("Confira abaixo sua nova senha, voc&ecirc; pode alter&aacute;-la quando quiser atrav&eacute;s do sistema.")?>
                                </p>
                                <h1 style="color:#132f3b;text-align:center"><strong><?=$this->senha;?></strong></h1>   
                                <br/>
    						</div>    						
    					</td>
    				</tr>
    			</tbody>
				<tfoot>
				<tr>
					<td>
						<div style="width: 94%; padding: 3%; background-color:#132f3b;border-top: 3px solid #f87902;color: #fff">
							<h4>
								<?=$this->translate("Informa&ccedil;&otilde;es para contato");?>
							</h4>
							<strong>Tel: </strong> <?=$this->getConfiguration('TELEFONEEMPRESA')?> <?=$this->translate("ou");?> <?=$this->getConfiguration('CELULAREMPRESA')?>&nbsp;&nbsp;&nbsp;
							<strong>Skype: </strong> <?=$this->getConfiguration('SKYPE')?><br/>
							<strong>Email: </strong> <?=$this->getConfiguration('EMAILEMPRESA')?><br/>
						</div>
					</td>
				</tr>
				</tfoot>
    		</table>
    		<p>&nbsp;</p>
		</div>
	</body>
</html>