<html>
	<head>
	
	</head>
	<body >
		<div style="width:100%;background-color: #444;" align="center">
			<p>&nbsp;</p>
    		<table   style="background-color: #fff" width="600">
    			<thead>
				<tr>
					<th>
						<div style="width: 94%; padding: 3%; background-color:#132f3b;border-bottom: 3px solid #f87902;">
							<?=$this->getConfiguration('LOGO')?>
						</div>
					</th>
				</tr>
    			</thead>
    			<tbody >
    				<tr >
    					<td>
    						<div style="padding: 5px">
    							<h4>
    								<strong>Houve um novo cadastro no sistema</strong>
    							</h4>
    							<br />                               
                                
                                <p> 
                                	O usuário <?=$this->nome?> acabou de se cadastrar no sistema, clique 
                                	<a target="_blank" href="http://<?=$_SERVER['HTTP_HOST']?>/admin/users/edit/<?=$this->id?>">aqui</a> para visualizar seus dados                                	
                                </p>
                                
    						</div>    						
    					</td>
    				</tr>
    			</tbody>  
    			<tfoot>
					<tr>
						<td>
							<div style="width: 94%; padding: 3%; background-color:#132f3b;border-top: 3px solid #f87902;color: #fff">
								<h4>
									<?=$this->translate("Informa&ccedil;&otilde;es para contato");?>
								</h4>
								<strong>Tel: </strong> <?=$this->getConfiguration('TELEFONEEMPRESA')?> <?=$this->translate("ou");?> <?=$this->getConfiguration('CELULAREMPRESA')?>&nbsp;&nbsp;&nbsp;
								<strong>Skype: </strong> <?=$this->getConfiguration('SKYPE')?><br/>
								<strong>Email: </strong> <?=$this->getConfiguration('EMAILEMPRESA')?><br/>
							</div>
						</td>
					</tr>
    			</tfoot>  		
    		</table>
    		<p>&nbsp;</p>
		</div>
	</body>
</html>