<div ng-controller="AuthorizeController as auth" class="col-md-12">
    <div class="card">
        <div class="header">
            <div class="row">
                <div class="col-md-8">
                    <h4 class="title">Gerenciador de Possibilidades</h4>
                    <p class="category text-justify">
                        Selecione quais as ações possíveis a um determinado recurso
                    </p>
                </div>
                <div class="col-md-4">
                    <button class="btn btn-link pull-right" type="button" data-toggle="collapse" data-target="#collapsePossibility" aria-expanded="true" aria-controls="collapsePossibility">
                        Exibir/Esconder Formulário
                    </button>
                </div>
            </div>
        </div>
        <div class="content">
            <div class="row">
                <div class="accordion col-md-12" id="accordionPossibilityForm">
                    <div id="collapsePossibility" class="row collapse  in" aria-expanded="true">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label>Recurso *</label>
                                    <select class="form-control" ng-model="resource" ng-value="resource">
                                        <option value="">Selecione...</option>
                                        <option ng-repeat="resource in resources" value="{{ resource.id }}">
                                            {{ resource.name }}
                                        </option>
                                    </select>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Ações</label>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <select class="form-control" ng-model="action" ng-value="action">
                                                <option value="">Selecione...</option>
                                                <option ng-repeat="action in actions" value="{{ action.id }}">
                                                    {{ action.name }}
                                                </option>
                                            </select>
                                        </div>
                                        <div class="col-md-6">
                                            <button ng-click="addPossibility()" class="form-control btn btn-success">
                                                <i class="pe-7s-upload"></i>&nbsp;Adicionar a ação à lista
                                            </button>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-12 form-group">
                                    <label>Lista de Ações</label>
                                    <table class="table table-hover">
                                        <thead>
                                            <tr>
                                                <th>Id</th>
                                                <th>Nome</th>
                                                <th>Remover</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr ng-repeat="act in acts">
                                                <td>{{ act.id }}</td>
                                                <td>{{ act.name }}</td>
                                                <td><button ng-click="rmv(act)" class="btn btn-danger"><i class="pe-7s-close-circle"></i></button></td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                            </div>
                        </div>
                        <div class="col-md-12">
                            <button type="button" ng-if="btnadd" ng-click="add()" class="btn btn-success pull-right">
                                Adicionar
                            </button>
                            <button type="button" ng-if="btnedit" ng-click="save(id)" class="btn btn-primary pull-right">
                                Atualizar
                            </button>
                            <button ng-click="clear()" class="btn btn-danger pull-right">
                                Cancelar
                            </button>
                        </div>
                    </div>
                </div>
                <hr/>
            </div>
            <div class="row">
                <hr/>
                <div class="col-md-8">
                    <h4 class="title">
                        Listagem de Registros
                    </h4>
                </div>
                <div class="col-md-4">
                    <div style="float: right;" class="btn-group">
                        <button ng-click="clear()" type="button" class="btn btn-success">
                            <i class="fa fa-plus"></i> Novo
                        </button>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-12">
                    <table class="table table-hover">
                        <thead>
                        <tr>
                            <th>Id</th>
                            <th>Recurso</th>
                            <th>Ações</th>
                        </tr>
                        </thead>
                        <tbody>
                            <tr ng-repeat="possibility in possibilities">
                                <td>{{ possibility.id }}</td>
                                <td><a href="/admin/resources/edit/{{ possibility.id }}">{{ possibility.name }}</td>
                                <td>
                                    <button class="btn btn-link pull-right form-control" type="button" data-toggle="collapse" data-target="#collapseAction{{ possibility.id }}" aria-expanded="false" aria-controls="collapseAction{{ possibility.id }}">
                                        {{ possibility.actions.length }} Disponíveis&nbsp;<i class="pe-7s-angle-down"></i>
                                    </button>
                                    <div class="accordion col-md-12" id="accordionPossibilityForm{{ possibility.id }}">
                                        <div id="collapseAction{{ possibility.id }}" class="table-full-width collapse" aria-expanded="false">
                                            <table class="table">
                                                <tbody>
                                                    <tr ng-repeat="action in possibility.actions">
                                                        <td>{{ action.name }}</td>
                                                        <td class="td-actions text-right">
                                                            <button ng-click="del(possibility.id,action.id)" type="button" rel="tooltip" title="" class="btn btn-danger btn-simple btn-xs" data-original-title="Remove">
                                                                <i class="fa fa-times"></i>
                                                            </button>
                                                        </td>
                                                    </tr>
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

