<?php
$em = $this->em;

/**
 * @var \Site\Entity\Banner[] $banners
 */
$banners = $em->getRepository('Site\Entity\Banner')->findByActive(1);
$selected = rand (0,count($banners)-1);

if(!empty($banners))
{
    $banner = $banners[$selected];
    ?>
    <header id="fh5co-header"
            class="fh5co-cover"
            role="banner"
            style="background-image:url('img/banner/<?=$banner->getImage()?>');"
            data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row">
                <div class="col-md-8 col-md-offset-2 text-center">
                    <div class="display-t">
                        <div class="display-tc animate-box" data-animate-effect="fadeIn">
                            <?php
                            if($banner->getTitle() != '') {
                                ?>
                                <h1 style="color: <?=$banner->getColor()?>"><?= $banner->getTitle() ?></h1>
                                <?php
                            }

                            if($banner->getSubtitle() != '') {
                                ?>
                                <h2 style="color: <?=$banner->getColor()?>"><?= $banner->getSubtitle() ?></h2>
                                <?php
                            }

                            if($banner->getText() != '') {
                                ?>
                                <p style="color: <?=$banner->getColor()?>"><?= $banner->getText() ?></p>
                                <?php
                            }

                            if($banner->getTitleButton() != '' && $banner->getLink() != '')
                            {
                                ?>
                                <p>
                                    <a class="btn btn-primary" href="<?=$banner->getLink()?>" target="_blank" style="color: <?=$banner->getColor()?> !important;" class="hero-link">
                                        <?= $banner->getTitleButton() ?>
                                    </a>
                                </p>
                                <?php
                            }
                            ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <?php
}
?>