<?php
/**
 * @var Activities\Entity\Activities[] $db_activities
 */
$em = $this->em;
$db_activities = $em->getRepository('Activities\Entity\Activities')->getOrderTime();

$weekdays = array(
    0 => array(
        'lg' => 'Domingo',
        'xs' => 'Dom'
    ),
    1 => array(
        'lg' => 'Segunda',
        'xs' => 'Seg'
    ),
    2 => array(
        'lg' => 'Terça',
        'xs' => 'Ter'
    ),
    3 => array(
        'lg' => 'Quarta',
        'xs' => 'Qua'
    ),
    4 => array(
        'lg' => 'Quinta',
        'xs' => 'Qui'
    ),
    5 => array(
        'lg' => 'Sexta',
        'xs' => 'Sex'
    ),
    6 => array(
        'lg' => 'Sábado',
        'xs' => 'Sab'
    )
);

if(!empty($db_activities))
{
    foreach($db_activities as $activity)
    {
        $w = explode(',',$activity->getWeekday());
        if(!empty($w))
        {
            foreach($w as $v)
            {
                $weekdays[$v]['activities'][] =  $activity;
            }
        }
    }
}

?>
<div id="fh5co-schedule" class="fh5co-bg" style="background-image: url('/img/img_bg_1.jpg');">
    <div class="container">
        <div class="row">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading animate-box">
                <h2>Horário das Atividades</h2>
            </div>
        </div>
        <div class="row animate-box">
            <div class="fh5co-tabs">
                <ul class="fh5co-tab-nav">
                    <?php
                    $count = 0;
                    foreach($weekdays as $k => $weekday)
                    {
                        if(!empty($weekday['activities']) && $count == 0){
                            $count++;
                        }

                        ?>
                        <li class="<?=($count==1)?'active':'';?>">
                            <a href="#" data-tab="<?=$k?>">
                                <span class="visible-xs"><?=$weekday['xs']?></span>
                                <span class="hidden-xs"><?=$weekday['lg']?></span>
                            </a>
                        </li>
                        <?php
                        if($count >= 1){
                            $count++;
                        }
                    }
                    ?>
                </ul>
                <?php
                if(!empty($weekdays))
                {
                    $count = 1;
                    ?>
                    <div class="fh5co-tab-content-wrap">
                        <?php
                        foreach($weekdays as $k => $weekday)
                        {
                            if(!empty($weekday['activities']) && $count == 0){
                                $count++;
                            }

                            /**
                             * @var Activities\Entity\Activities[] $acts
                             */
                            $acts = $weekday['activities'];

                            if(!empty($acts))
                            {
                                ?>
                                <div class="fh5co-tab-content tab-content <?=($k == 1)?'active':''?> "
                                     data-tab-content="<?=$k?>">
                                    <ul class="class-schedule">
                                        <?php
                                        foreach($acts as $act)
                                        {
                                            ?>
                                            <li class="text-center">
                                                <span>
                                                    <img src="<?=$act->getIcon()?>" class="img-responsive" alt="">
                                                </span>
                                                <span class="time">
                                                    <?=$act->getStartHour();?> - <?=$act->getFinishHour();?>
                                                </span>
                                                <h4>
                                                    <?=$act->getName()?>
                                                </h4>
                                                <small>
                                                    <?=$act->getTeacher()?>
                                                </small>
                                            </li>
                                            <?php
                                        }
                                        ?>
                                    </ul>
                                </div>
                                <?php
                            }

                            if($count >= 1){
                                $count++;
                            }
                        }
                        ?>
                    </div>
                    <?php
                }
                ?>
            </div>
        </div>
    </div>
</div>