<?php
$texto  = $this->getText('PROFISSIONAIS');
$limit  = $this->limit;
$rand   = $this->rand;
?>
<div id="fh5co-trainer">
    <div class="container">
        <div class="row animate-box">
            <div class="col-md-8 col-md-offset-2 text-center fh5co-heading">
                <h2><?=$texto->getTitle()?></h2>
                <p>
                    <?=$texto->getText()?>
                </p>
            </div>
        </div>
        <?php
        /**
         * @var \Register\Entity\Person[] $db_teachers
         * @var \Register\Entity\Image[] $db_imgs
         * @var \Register\Entity\ReferenceImage $db_reference_image
         */
        $db_teachers = $em->getRepository('Register\Entity\Person')->getByProfile('teacher',$limit,$rand);
        $db_reference_image = $em->getRepository('Register\Entity\ReferenceImage')->findOneByChave('person');
        if(!empty($db_teachers))
        {
            ?>
            <div class="row">
                <?php
                foreach ($db_teachers as $db_teacher)
                {
                    $db_imgs = $em->getRepository('Register\Entity\Image')->findBy(array(
                        'referenceImage'    => $db_reference_image,
                        'person'            => $db_teacher
                    ));

                    $img_selected = null;
                    $featured = false;
                    if(!empty($db_imgs))
                    {
                        foreach($db_imgs as $db_img)
                        {
                            if($db_img->getFeatured())
                            {
                                $featured = true;
                                $img_selected = $db_img->getImage();
                            }else if($featured == false)
                            {
                                $img_selected = $db_img->getImage();
                            }
                        }
                    }

                    if($img_selected){
                        $url_img = "img/images/".$img_selected;
                    }else{
                        $url_img = null;
                    }

                    $number = count($db_teachers);
                    switch ($number)
                    {
                        case 1:
                            $collumn = 'col-md-4 col-md-offset-4 col-sm-4 col-sm-offset-4';
                            break;
                        case 2:
                            $collumn = 'col-md-6 col-sm-6';
                            break;
                        case 3:
                            $collumn = 'col-md-4 col-sm-4';
                            break;
                    }

                    $url_teacher = $this->url('person-page',array('friendly-url' => $db_teacher->getFriendlyUrl()));

                    ?>
                    <div class="<?=$collumn?> animate-box">
                        <div class="trainer">
                            <a href="<?=$url_teacher;?>">
                                <img class="img-responsive" src="<?=$url_img?>" alt="trainer">
                            </a>
                            <div class="title">
                                <h3>
                                    <a href="<?=$url_teacher;?>"><?=$db_teacher->getName()?></a>
                                </h3>
                                <span><?=$db_teacher->getSpecialty()?></span>
                            </div>
                            <div class="desc text-center">
                                <ul class="fh5co-social-icons">
                                    <?php
                                    if($db_teacher->getInstagram() != '') {
                                        ?>
                                        <li>
                                            <a target="_blank" href="<?= $db_teacher->getInstagram() ?>">
                                                <i class="icon-instagram"></i>
                                            </a>
                                        </li>
                                        <?php
                                    }

                                    if($db_teacher->getFacebook() != '')
                                    {
                                        ?>
                                        <li>
                                            <a target="_blank" href="<?=$db_teacher->getFacebook()?>">
                                                <i class="icon-facebook"></i>
                                            </a>
                                        </li>
                                        <?php
                                    }
                                    ?>
                                </ul>
                            </div>
                        </div>
                    </div>
                    <?php
                }
                ?>
            </div>
            <?php
        }
        ?>
    </div>
</div>