<?php
/**
 * @var \Register\Entity\Person $db_company
 */
$db_company = $this->company;
?>
<div class="container-fluid">
    <div class="row">
        <ol class="breadcrumb">
            <li><a href="<?=$this->url('admin');?>"><i class="pe-7s-graph"></i>&nbsp;Dashboard</a></li>
            <li class="active">Painel</li>
        </ol>
        <div class="col-md-12">
            <h2 style="margin: 0px 0px 20px 0px;">Painel Data Frete <small>- Aqui você tem as principais funcionalidades do Data Frete</small></h2>
        </div>
        <div class="col-md-12">
            <ul class="nav nav-tabs" id="myTab" role="tablist">
                <li class="item active">
                    <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab" aria-controls="home" aria-selected="false">Rastreio</a>
                </li>
                <li class="item">
                    <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Consulta Frete</a>
                </li>
            </ul>
            <div class="tab-content" id="myTabContent">
                <div class="tab-pane fade active in" id="home" role="tabpanel" aria-labelledby="home-tab">
                    <div class="card">
                        <div class="header">
                            <h4 class="title">Consultar Frete</h4>
                        </div>
                        <div class="content">
                            <a class="btn btn-primary" href="<?=$this->url('rastreio',array('company' => $db_company->getFriendlyUrl()))?>">Acessar Painel de Rastreio</a>
                        </div>
                    </div>
                </div>
                <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                    <div class="row">
                        <?=$this->partial('consulta-frete');?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
