
<?=$this->partial('partial/form',array(
	'type'          => 'edit',
	'action'        => $this->action,
	'acao'          => 'editar registro',
	'form'          => $this->form,
	'title'         => $this->title,
	'controller'    => $this->controller,
	'route'         => $this->route,
	'entity'        => $this->entity,
	'id'            => $this->id,
    'em'            => $this->em,
    'fk'            => $this->fk,
    'fk_id'         => $this->fk_id,
));
?>