<?php
function camel2dashed($className) {
    return strtolower(preg_replace('/([^A-Z-])([A-Z])/', '$1-$2', $className));
}
$controller = camel2dashed($this->_listView['controller']);

$link['new'] = $this->url($this->_listView['route'], array(
    'controller' => $controller,
    'action' => 'new'
));

$chave = $this->_listView['controller'];

//Preferencia de redirecionamento
if(isset($goto[$chave])){
	if(!$this->personPermission('modulos',$this->_listView['controller'],'listAll')) {
		header('Location: '.$goto[$chave]);
		exit();
	}
}else{
	if(!$this->personPermission('modulos',$this->_listView['controller'],'listAll')) {
		header('Location: /not-have-permission');
		exit();
	}
}


?>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
                <li><a href="/admin"><i class="fa fa-dashboard"></i> Home</a></li>
                <li class="active"><?=$this->_listView['title']?></li>
            </ol>
            <?php $this->getAdminFlashMessenger();?>
        </div>
        <div class="col-md-12">
            <div class="card">
                <div class="header">
                    <div class="row">
                        <div class="col-md-8">
                            <h4 class="title">
                                <?=$this->_listView['title']?> - <small>Listagem de Registros</small>
                            </h4>
                        </div>
                        <div class="col-md-4">
                            <div style="float: right; margin-right: 10px;" class="btn-group">
                                <a
                                        href="<?php echo $this->url($this->_listView['route'],array('action'=>'new')); ?>">
                                    <button type="button" class="btn btn-success">
                                        <i class="fa fa-plus"></i> Novo
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content">
                    <div class="row">
                        <div class="col-md-12">
                            <?php
                            $method_filter = 'filter'.ucwords($controller);
                            try{
                                echo $this->$method_filter();
                            }catch (Exception $e){}
                            ?>
                            <table class="table table-hover">
                                <?=$this->partial('partial/header');?>
                                <?=$this->partial('partial/body');?>
                            </table>
                        </div>
                        <div class="col-md-12">
                            <?=$this->paginationControl($this->data,'Sliding','partials/paginator'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


