<?=$this->partial('partial/form',array(
    'type' => 'new',
    'acao' => 'adicionar registro',
    'form' => $this->form,
    'title' => $this->title,
    'controller' => $this->controller,
    'route' => $this->route,
    'entity' => $this->entity,
    'id' => $this->id,
    'cities' => $this->cities,
    'states' => $this->states,
    'em' => $this->em,
    'fk' => $this->fk,
    'fk_id' => $this->fk_id,
));
?>