<div class="modal fade" id="login-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title" id="myModalLabel">Faça o Login</h4>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div class="col-md-12">
                        <p>Você precisa logar para utilizar as ferramentas do sistema!</p>
                        <hr/>
                    </div>
                    <div class="col-md-12">
                        <form id="form-etiqueta" method="post" action="<?=$this->url('person-auth');?>">
                            <input type="hidden" name="redirect" value="<?=$this->url('print-etiqueta');?>">
                            <div class="row">
                                <div class="col-md-6 form-group">
                                    <label>Usuário / E-mail</label>
                                    <input type="email" name="email" value="" class="form-control" placeholder="Seu E-mail" required>
                                </div>
                                <div class="col-md-6 form-group">
                                    <label>Senha</label>
                                    <input type="password" name="password" value="" class="form-control" required>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-12">
                                    <a style="text-decoration: underline;" href="<?=$this->url('lostpassword').'?redirect='.$this->redirect?>">
                                        Esqueci minha senha!
                                    </a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <div class="row">
                    <div class="col-md-6">
                        <a href="<?=$this->url('person-register').'?redirect='.$this->redirect?>" class="btn btn-primary pull-left" >
                            <i class="fa fa-plus"></i>&nbsp;Ainda não possuo cadastro!
                        </a>
                    </div>
                    <div class="col-md-6">
                        <button type="submit" form="form-etiqueta"  class="btn btn-success pull-right" >
                            <i class="fa fa-print"></i>&nbsp;Logar
                        </button>
                        <button type="button" class="btn btn-danger pull-right" data-dismiss="modal">
                            <i class="fa fa-close"></i>&nbsp;Fechar
                        </button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>