<?php
$urlPattern = $_SERVER['REQUEST_URI'];

$formatUrl = function ($page) use ($urlPattern) {

            if (!preg_match('/page/', $urlPattern))
                return $urlPattern . '/page/' . (int) $page;

            else
                return preg_replace('@/page/\d@', '/page/' . (int) $page, $urlPattern);
        };
        
if ($this->pageCount){?>
    <div class="pagination pagination-centered">
        <ul class="pagination">
    	<?php 
    	if (isset($this->previous)){ ?>
            <li class="paginate_button">
            	<a href="<?php echo $formatUrl($this->previous); ?>">«</a>
        	</li>
        <?php 
    	}else{ 
        ?>
            <li class="paginate_button disabled">
            	<a href="#">«</a>
            </li>
		<?php 
    	}
 
        foreach ($this->pagesInRange as $page){
            if ($page != $this->current){
            ?>
                <li class="paginate_button">
                    <a href="<?php echo $formatUrl($page); ?>"><?php echo $page; ?></a>
                </li>      
            <?php 
            }else{ 
            ?>
                <li class="paginate_button active">
                    <a href="#"><?php echo $page; ?></a>
                </li>
        <?php 
            }         
        }
        ?>

        <?php 
        if(isset($this->next)){ 
        ?>
    		<li  class="paginate_button next" >
    			<a href="<?php echo $formatUrl($this->next); ?>">»</a>
    		</li>
        <?php 
		}else{ 
		?>
    		<li class="paginate_button next disabled">
            	<a href="#">»</a>
        	</li>
        <?php 
        } 
        ?>
	</ul>
</div>
<?php 
} 
?>