<section class="content-header">
    <h1>
        Dashboard
        <small>Control panel</small>
    </h1>
    <ol class="breadcrumb">
        <li><a href="<?=$this->url('admin')?>"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
    </ol>
</section>
<div class="container">
    <div class="row">
        <div class="col-md-12 flashMessages">

            <?php
            $flash = $this->flashMessenger();
            echo $flash->render('error', array(
                'alert',
                'alert-dismissible',
                'alert-danger'
            ));
            echo $flash->render('info', array(
                'alert',
                'alert-dismissible',
                'alert-info'
            ));
            echo $flash->render('default', array(
                'alert',
                'alert-dismissible',
                'alert-warning'
            ));
            echo $flash->render('success', array(
                'alert',
                'alert-dismissible',
                'alert-success'
            ));

            ?>
        </div>
    </div>
</div>
<br />
<?
$person = $this->PersonIdentity('Person');
if($person->isIsAdmin()) {
    ?>
    <section class="content">
        <div class="row">
            <?=$this->partial('partial/admin-container.phtml'); ?>
        </div>
    </section>
    <?
}
?>
