<div id="ribbon">
    <span class="ribbon-button-alignment">
        <span id="refresh" class="btn btn-ribbon" data-action="resetWidgets" data-title="refresh"  rel="tooltip" data-placement="bottom" data-original-title="<i class='text-warning fa fa-warning'></i> Warning! This will reset all your widget settings." data-html="true">
            <i class="fa fa-refresh"></i>
        </span>
    </span>
    <ol class="breadcrumb">
        <li>Home</li><li>Dashboard</li>
    </ol>
</div>
<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa-fw fa fa-home"></i> Dashboard <span>> Meu Dashboard</span>
            </h1>
        </div>
    </div>
    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-sm-12">
                <div class="jarviswidget" id="wid-id-0"
                     data-widget-togglebutton="false"
                     data-widget-editbutton="false"
                     data-widget-fullscreenbutton="false"
                     data-widget-colorbutton="false"
                     data-widget-deletebutton="false">
                    <header>
                        <span class="widget-icon">
                            <i class="fa fa-wrench txt-color-darken"></i>
                        </span>
                        <h2>Ferramentas Smart Envios</h2>
                        <ul class="nav nav-tabs pull-right in" id="myTab">
                            <li class="active">
                                <a data-toggle="tab" href="#s1">
                                    <i class="fa fa-file-text-o"></i>
                                    <span class="hidden-mobile hidden-tablet">Etiquetas</span>
                                </a>
                            </li>
                            <li class="disabled">
                                <a data-toggle="tab" href="#s2">
                                    <i class="fa fa-truck"></i>
                                    <span class="hidden-mobile hidden-tablet">Rastreio</span>
                                </a>
                            </li>
                        </ul>
                    </header>
                    <div class="no-padding">
                        <div class="widget-body">
                            <div id="myTabContent" class="tab-content">
                                <div class="tab-pane fade active padding-bottom-10 in" id="s1">
                                    <div class="widget-body-toolbar bg-color-white">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="col-md-4 bg-color-darken padding-bottom-10 padding-top-10">
                                                    <h4 class="no-padding no-margin txt-color-white">
                                                        <strong>
                                                            <i class="fa fa-file-text-o"></i>&nbsp;Etiqueta Nota Fiscal
                                                        </strong>
                                                    </h4>
                                                    <hr/>
                                                    <p class="txt-color-white">
                                                        Faça upload do XML de uma nota fiscal e imprima etiquetas!
                                                    </p>
                                                    <a class="btn btn-primary" href="<?=$this->url('painel-etiqueta-nfe');?>">
                                                        Acessar
                                                    </a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="s2">
                                    <div class="widget-body-toolbar bg-color-white">
                                        <div class="row">
                                            <div class="col-md-12">
                                                <div class="col-md-4 bg-color-darken padding-bottom-10 padding-top-10">
                                                    <h4 class="no-padding no-margin txt-color-white">
                                                        <strong>
                                                            <i class="fa fa-truck"></i>&nbsp;Painel de Rastreio
                                                        </strong>
                                                    </h4>
                                                    <hr/>
                                                    <p class="txt-color-white">
                                                        Acesse o painel de rastreio e saíba mais sobre a logistica
                                                    </p>
                                                    <button class="btn btn-primary">
                                                        Acessar
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="tab-pane fade" id="s3">
                                    <div class="widget-body-toolbar bg-color-white smart-form" id="rev-toggles">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
</div>
