<?php

namespace Catalog\Controller;

use Base\Controller\CrudController;

class ProductController extends CrudController
{
    protected $route;

    public function __construct() 
    {
        $this->title = "Produto";

        $this->table = 'Product';
        $this->entity = 'Catalog\Entity\\'.$this->table ;
        $this->service = 'Catalog\Service\\'.$this->table ;
        $this->form = 'Catalog\Form\\'.$this->table ;
        $this->controller = "Product";
        $this->route = "product/default";

        $this->_listView = array(
            'title' => $this->title,
            'icon' => 'fa fa-share-alt-square',
            'route' => $this->route,
            'controller' => $this->controller,
            'actions' => array(
                'enable' =>true,
                'customs' => array(
                    'skus' => array(
                        'rota' => 'sku-join',
                        'title' => 'Skus',
                        'appear-title' => true,
                        'enable' => false,
                        'class' => 'btn btn-info',
                        'icon' => 'pe-7s-box2',
                        'type'  => 'join',
                        'join' => array(
                            'entity'    => 'Catalog\Entity\Sku',
                            'pk'        => 'id',
                            'fk'        => 'product'
                        ),
                        'group' => false,
                    ),
                ),
                'defaults' => array(
                    'edit' => array(
                        'enable' => true,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-edit'
                    ),
                    'delete' => array(
                        'enable' => true,
                        'class' => 'btn btn-danger decision',
                        'icon' => 'fa fa-trash'
                    ),
                    'view' => array(
                        'enable' => false,
                        'class' => 'btn btn-info',
                        'icon' => 'fa fa-eye'
                    ),
                ),
            ),
            'fields' => array(
                'id'=>array(
                    'label' => 'Id',
                    'list' => true,
                ),
                'name'=>array(
                    'label' => 'Nome',
                    'list' => true,
                ),
                'company' => array(
                    'label' => 'Empresa',
                    'list' => true
                )
            ),
        );
    }

    public function  indexAction($list = null)
    {
        return parent::indexAction($list); // TODO: Change the autogenerated stub
    }

    public function editAction($request = null)
    {
        return parent::editAction($request); // TODO: Change the autogenerated stub
    }

    public function newAction($request = null)
    {
        return parent::newAction($request); // TODO: Change the autogenerated stub
    }
}
