<div class="row">
    <div class="col-md-4 col-md-offset-8">
        <div class="card">
            <div class="header">
                <div class="row">
                    <div class="col-md-12">
                        <h4 style="margin: 0"><i class="pe-7s-search"></i>&nbsp;Filtro</h4>
                    </div>
                </div>
            </div>
            <div class="content">
                <form method="post" name="filter-form" action="">
                    <div class="row">
                        <div class="col-md-12 form-group">
                            <label>Nome</label>
                            <input name="person_name" id="inputPersonName" class="form-control" value="<?= $_POST['person_name'] ?>">
                            <input type="hidden" name="person" id="inputPerson" value="<?= $_POST['person'] ?>">
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">
                            <button class="btn btn-success" >Filtrar</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>

    </div>
</div>
<?php

/**
 * @var \Register\Entity\Person[] $db_persons
 * @var \Register\Entity\Person $db_login
 */
$functions = new \Base\Controller\BaseFunctions();
$db_login = $this->PersonIdentity('Person');
$db_persons = $this->em->getRepository('Register\Entity\Person')->findByCompany($db_login->getCompany());
$names = array();
foreach($db_persons as $db_person){
    $names[] = array('label' => $functions->formatarTexto($db_person->getName()),'value' =>$db_person->getId());
}
$names = json_encode($names);

?>
<script>
    $(document).ready(function(){
        <?php
        if(isset($names) && $names != '')
        {
            ?>
            let Json = '<?=$names?>';
            var users = JSON.parse(Json);

            $("#inputPersonName").autocomplete({
                source: users,
                open: function (event, ui) {
                    $('#inputPerson').val('');
                },
                select: function(event, ui) {
                    $('#inputPersonName').val(ui.item.label);
                    $('#inputPerson').val(ui.item.value);
                    return false;
                }
            }).blur(function(){
                if($("#inputPersonName").val() == '')
                {
                    $("#inputPersonName").val('');
                    $('#inputPerson').val('');
                }

                if($('#inputPerson').val() == '')
                {
                    $("#inputPersonName").val('');
                }
            });
            <?php
        }
        ?>
    });
</script>