<?php
$db_entity = $this->entity;
$HASHMAP = $this->data_page;
if($this->aspectRatio) {
    $aspectRatio = $this->aspectRatio;
}else{
    $aspectRatio = null;
}
if($this->db_person){
    $db_person = $this->db_person;
}else{
    $db_person = $this->PersonIdentity('Person');
}

$em = $this->em;
?>

<div class="col-md-12">
    <?php $this->getAdminFlashMessenger();?>
</div>

<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa fa-plus-square"></i> Cadastro de Imagens
            </h1>
        </div>
    </div>
    <section id="widget-grid" class="">
        <div class="row">
            <article class="col-sm-3 col-md-3 col-lg-3">
                <div class="jarviswidget" id="wid-id-1" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-filter"></i> </span>
                        <h2>Filtrar</h2>
                    </header>
                    <div>
                        <div class="jarviswidget-editbox">
                        </div>
                        <div class="widget-body no-padding">
                            <form class="smart-form" id="form-filter-image" method="post" action="">
                                <input type="hidden" id="grid" name="grid" value="<?=$_POST['grid']?>">
                                <fieldset>
                                    <?php
                                    /**
                                     * @var \Register\Entity\CategoryImage[] $categories
                                     */
                                    if($db_person instanceof  $db_person) {
                                        $categories = $em->getRepository('Register\Entity\CategoryImage')->findBy(array(
                                            'person' => $db_person->getId()
                                        ));
                                    }else{
                                        $categories = $em->getRepository('Register\Entity\CategoryImage')->findByPerson(null);
                                    }
                                    ?>
                                    <section>
                                        <label class="label">Categoria</label>
                                        <label class="input">
                                            <select class="form-control" name="category">
                                                <option value="">Gerais</option>
                                                <?php
                                                foreach($categories as $category){
                                                    ?>
                                                    <option <?=($_POST['category'] == $category->getId())?'selected':'';?> value="<?=$category->getId()?>"><?=$category->getName()?></option>
                                                    <?php
                                                }
                                                ?>
                                            </select>
                                        </label>
                                    </section>
                                    <section>
                                        <label class="label">
                                            <i class="fa fa-search"></i> Pesquisar
                                        </label>
                                        <label class="input">
                                            <input class="form-control" name="search" value="<?=$_POST['search']?>">
                                        </label>
                                    </section>
                                </fieldset>
                                <footer>
                                    <button form="form-filter-image" type="submit" class="btn btn-primary">
                                        Filtrar
                                    </button>
                                </footer>
                            </form>
                        </div>
                    </div>
                </div>
            </article>
            <article class="col-sm-9 col-md-12 col-lg-9">
                <div class="jarviswidget" id="wid-id-2" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-custombutton="false">
                    <header>
                        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
                        <h2>Cadastro de Imagens</h2>
                    </header>
                    <div>
                        <div class="jarviswidget-editbox">
                        </div>
                        <div class="widget-body no-padding">
                            <form id="image-form" role="form" method="post" action="<?=$this->url('image/defaults',array('controller' => 'image','action' => 'new-custom'));?>">
                                <input type="hidden" id="id" name="reference_id" value="<?=$this->id?>"/>
                                <input type="hidden" id="person" name="person" value="<?=$db_person->getId()?>"/>
                                <input type="hidden" id="reference" name="reference" value="<?=$this->controller?>"/>
                                <div class="col-md-7">
                                    <div class="row">
                                        <div class="col-md-12">
                                            <label>Incluir Nova Categoria</label>
                                            <div class="input-group">
                                        <span onclick="addCategory($('#new-category').val())" class="input-group-addon btn btn-primary" id="basic-addon">
                                            <i class="fa fa-plus"></i>
                                        </span>
                                                <input type="text"
                                                       class="form-control"
                                                       name="new-category"
                                                       id="new-category"
                                                       aria-describedby="basic-addon"
                                                       placeholder="Ex. Fachada, Festa, Palestra...">
                                            </div>
                                            <hr />
                                        </div>

                                        <?php
                                        $categories = $em->getRepository('Register\Entity\CategoryImage')->findByPerson($db_person);
                                        ?>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Categoria</label>
                                                <select name="category" id="category" class="form-control">
                                                    <option value="-1">Geral</option>
                                                    <?php
                                                    if(!empty($categories))
                                                    {
                                                        foreach($categories as $categoria)
                                                        {
                                                            echo '<option value="'.$categoria->getId().'">'.$categoria->getName().'</option>';
                                                        }
                                                    }
                                                    ?>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Destaque</label>
                                                <select class="form-control" name="featured">
                                                    <option value="0">Não</option>
                                                    <option value="1">Sim</option>
                                                </select>
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label>Legenda</label>
                                                <textarea id="legenda" name="title" class="form-control" placeholder=""></textarea>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-5">
                                    <div class="form-group">
                                        <label for="image_input">Imagem</label>
                                        <input class="form-control" type="file" id="image_input" accept="image/*" onchange="cropImage(event)">
                                    </div>
                                    <div id="image_load"></div>
                                    <input type="hidden" id="image" name="image" value="" />
                                    <hr />
                                </div>
                            </form>
                        </div>

                    </div>
                    <div class="widget-footer padding-bottom-10">
                        <button type="button" class="btn btn-primary" onclick="cadastrar()">Cadastrar</button>
                        <button id="cancel-crop" onclick="cancelCrop()" type="button" class="btn btn-danger">Cancelar</button>
                    </div>
                </div>
            </article>
        </div>
        <div class="row">
            <article class="col-sm-12">
                <div class="jarviswidget jarviswidget-color-blueDark" id="wid-id-0" data-widget-editbutton="false">
                    <header>
                        <span class="widget-icon">
                            <i class="fa fa-image"></i>
                        </span>
                        <h2>
                            Imagens
                        </h2>
                    </header>
                    <div class="widget-header">
                        <div class="btn-group" data-toggle="btn-toggle">
                            <button onclick="$('#grid').val('lg');$('#form-filter-image').submit();" class="btn <?=(isset($_POST['grid']) && $_POST['grid'] == 'lg' || !isset($_POST['grid']))?'btn-primary':''?>">
                                <i class="fa fa-th-large"></i>
                            </button>
                            <button onclick="$('#grid').val('sm');$('#form-filter-image').submit();" class="btn <?=(isset($_POST['grid']) && $_POST['grid'] == 'sm')?'btn-primary':''?>">
                                <i class="fa fa-th"></i>
                            </button>
                        </div>
                    </div>
                    <?
                    /**
                     * @var \Register\Entity\CategoryImage $category
                     * @var \Register\Entity\ReferenceImage $reference
                     * @var \Register\Entity\Image[] $images
                     */

                    $where .= 'i.person = '.$db_person->getId();

                    $reference = $em->getRepository('Register\Entity\ReferenceImage')->findOneByChave($this->controller);
                    if(!($reference instanceof \Register\Entity\ReferenceImage))
                    {
                        $reference = new \Register\Entity\ReferenceImage();
                        $reference->setChave($this->controller);
                        $reference->setName($this->controller);

                        $em->persist($reference);
                        $em->flush();
                    }

                    $where .= ' AND i.referenceImage = '.$reference->getId();
                    if($this->id){
                        $where .= ' AND i.reference_id = '.$this->id;
                    }else{
                        $where .= ' AND i.reference_id IS NULL';
                    }

                    if(isset($_POST['category']) && $_POST['category'] != '')
                    {
                        $category = $em->getRepository('Register\Entity\CategoryImage')->findOneById($_POST['category']);

                        $where .= ' AND i.categoryImage = '.$category->getId();
                    }

                    if(isset($_POST['search']) && $_POST['search'] != '')
                    {
                        $where .= " AND i.title LIKE '%".$_POST['search']."%'";
                    }

                    $alias = 'i';
                    $tabela = 'Register\Entity\Image';

                    $qb = $em->createQueryBuilder();
                    $qb->select(array(
                        $alias
                    ))
                        ->from($tabela,$alias)
                        ->where($where);

                    $images = $qb->getQuery()->getResult();

                    $col = (isset($_POST['grid']) && $_POST['grid'] == 'sm')?'col-md-2 col-sm-2 col-xs-2':'col-md-4 col-sm-4 col-xs-4';

                    ?>
                    <div class="widget-body">
                        <div class="row">
                            <div class="col-md-12 gal-container">
                                <?
                                if(!empty($images)){
                                    $i = 0;
                                    foreach($images as $image)
                                    {
                                        ?>
                                        <div id="bx-img-<?=$image->getId()?>" class="<?=$col?> gal-item">
                                            <div class="box">
                                                <button onclick="deleteImg(<?=$image->getId()?>)" class="btn btn-danger btn-sm btn-delete-image">
                                                    <i class="fa fa-close"></i>
                                                </button>
                                                <a class="img_list_item" href="#" style="background-image: url('/img/images/<?=$image->getImage()?>');" data-toggle="modal" data-target="#<?=$i?>">
                                                    <?php
                                                    if($image->getFeatured())
                                                    {
                                                        ?>
                                                        <i title="Destaque" class="fa fa-star featured-icon"></i>
                                                        <?php
                                                    }
                                                    ?>
                                                </a>
                                                <div class="modal fade" id="<?=$i?>" tabindex="-1" role="dialog">
                                                    <div class="modal-dialog modal-lg" role="document">
                                                        <div class="modal-content">
                                                            <?php
                                                            if($image->getFeatured())
                                                            {
                                                                ?>
                                                                <i title="Destaque" class="fa fa-star featured-icon"></i>
                                                                <?php
                                                            }
                                                            ?>

                                                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button>
                                                            <div class="modal-body">
                                                                <div align="center">
                                                                    <img class="img-responsive" src="/img/images/<?=$image->getImage()?>">
                                                                </div>
                                                            </div>
                                                            <?php
                                                            if($image->getTitle() != '')
                                                            {
                                                                ?>
                                                                <div class="col-md-12 description">
                                                                    <h4><?=$image->getTitle()?></h4>
                                                                </div>
                                                                <?
                                                            }
                                                            ?>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <?
                                        $i++;
                                    }
                                }else{
                                    ?>
                                    <div class="col-md-12">
                                        <div class="alert alert-primary text-center" role="alert">
                                            Não há imagens cadastradas
                                        </div>
                                    </div>
                                    <?php
                                }
                                ?>
                            </div>
                        </div>
                    </div>
                </div>
            </article>
        </div>
    </section>
</div>

<div class="modal fade" id="cropModal" tabindex="-1" role="dialog" aria-labelledby="cropLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Recorte a Imagem</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="row">
                    <div id="content-crop-box" class="col-md-12">
                        <img class="img-responsive" id="output"/>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick="cancelCrop()">Fechar</button>
                <button type="button" class="btn btn-primary" onclick="crop()">Recortar</button>
            </div>
        </div>
    </div>
</div>
<style>
    img {
        max-width: 100%;
    }

    .cropper-crop{
        display:none;
    }

    .cropper-container{
        width: 100% !important;
        float: left !important;
    }

    .box{
        position: relative;
    }

    .btn-delete-image{
        position: absolute;
        top: 0px;
        left: 0px;
        z-index: 99;
        opacity: 0.5;
    }

    .btn-delete-image:hover{
        opacity: 1;
    }

    .featured-icon{
        position: absolute;
        top: 5px;
        left: 5px;
        z-index: 99;
        opacity: 1;
        color: #f1a417;
        font-size: 30px;
    }

    .img_list_item {
        background-position: center;
        background-size: cover;
        width: 100%;
        float: left;
        height: 200px;
        margin-bottom: 25px;
    }
</style>
<script>
    $(document).ready(function(){
        $("#cancel-crop").hide();

        $('#new-category').keypress(function(e) {
            if(e.which == 13) {
                e.preventDefault();
                $("#basic-addon").trigger('click');
            }
        });

    });

    function cancelCrop() {
        location.reload();
    }

    function cadastrar(){
        if($("#image").val() != ''){
            $("#image-form").submit();
        }else{
            alert('Você precisa selecionar e recortar a imagem!');
        }
    }

    var cropImage = function(event){
        $('#cropModal').modal();
        setTimeout(function () {
            loadFile(event);
        },1000);
    }

    var loadFile = function(event) {
        var reader = new FileReader();
        reader.onload = function(){
            var output = document.getElementById('output');
            output.src = reader.result;
            var $image = $('#output');

            $image.cropper({
                zoomOnWheel:false,
                <?=($aspectRatio)?'aspectRatio: '.$aspectRatio.',':'';?>
                crop: function(event) {
//                    console.log(event.detail.x);
//                    console.log(event.detail.y);
//                    console.log(event.detail.width);
//                    console.log(event.detail.height);
//                    console.log(event.detail.rotate);
//                    console.log(event.detail.scaleX);
//                    console.log(event.detail.scaleY);
                }
            });
            var cropper = $image.data('cropper');
        };
        reader.readAsDataURL(event.target.files[0]);
    };

    var crop = function () {
        var output = $("#output");
        output.cropper('getCroppedCanvas').toBlob(function (blob) {
            var formData = new FormData();
            formData.append('croppedImage', blob);
            $.ajax('<?=$this->url('image/defaults',array('controller' => 'image','action' => 'recortar'));?>',{
                method: "POST",
                dataType: 'json',
                data: formData,
                processData: false,
                contentType: false,
                success: function (o) {
                    var object = o;
                    var image = object.image;
                    var image_name = object.image_name;
                    $("#image_load").html('<div align="center"><img style="max-height: 400px" class="img-responsive thumbnail" src="'+image+'"></div>');
                    $("#image").val(image_name);
                    $("#image_input").parent().remove();
                    $('#cropModal').modal('hide');
                    $("#cancel-crop").fadeIn('slow');
                },
                error: function () {
                    console.log('Upload error');
                }
            },'Json');
        });
    }

    function addCategory(newCategory) {
        var categories;
        var name = newCategory;
        var chave = encodeURI(newCategory);
        var person = "<?=$db_person->getId();?>";

        if(newCategory.trim() == '')
        {
            $('#new-category').parent().attr('class','input-group has-error');
            $('#new-category').focus();
            return false;
        }else{
            $('#new-category').parent().attr('class','input-group has-success');
        }

        $.ajax({
            url: '/api/category-image',
            type: "GET",
            async: false,
            data: {
                'filter': [
                    {
                        'field': 'name',
                        'where': 'AND',
                        'type': 'LIKE',
                        'value': newCategory
                    },
                    {
                        'field': 'person',
                        'where': 'AND',
                        'type': 'eq',
                        'value': person
                    }
                ]
            },
            success: function (o) {
                categories = o._embedded.category_image;
            },
            error: function () {
                alert('Erro ao buscar a categoria');
            },
            dataType: "json"
        });

        if(categories.length < 1){
            $.ajax({
                url: '/api/category-image',
                cache : false,
                type : 'POST',
                contentType : 'application/json',
                data : JSON.stringify({
                    'name'      : name,
                    'chave'     : chave,
                    'person'    : person,
                }),
                success : function(data, status, xhr) {
                    var html_option = '<option value="'+data.id+'">'+data.name+'</option>';
                    $("#category").append(html_option);
                    $("#category").val(data.id);
                    $("#new-category").val('');
                    $('#category').parent().attr('class','form-group has-success');
                    $("#legenda").focus();
                },
                error: function () {
                    alert('Erro ao incluir a categoria');
                },
                dataType: "json"
            });
        }else{
            alert("A Categoria já existe!");
        }
    }

    $('#cropModal').on('hidden.bs.modal', function (e) {
        if($("#image").val() == ''){
            location.reload();
        }
    });

    function deleteImg(img_id) {
        bootbox.confirm({
            message: "Deseja excluir a imagem?",
            buttons: {
                cancel: {
                    label: 'Não',
                    className: 'btn-danger'
                },
                confirm: {
                    label: 'Sim',
                    className: 'btn-success btnConfirm',
                }
            },
            callback: function (result) {
                if(!result){
                    this.modal('hide');
                }else{
                    $.ajax({
                        url: '/api/image/'+img_id,
                        cache : false,
                        type : 'DELETE',
                        contentType : 'application/json',
                        success : function(data, status, xhr) {
                            $("#bx-img-"+img_id).remove();
                        },
                        error: function () {
                            console.log('Erro ao excluir a imagem');
                        },
                        dataType: "json"
                    });
                }
            }
        });
    }
</script>

